### PR TITLE
Fix HotMovies Scraper

### PR DESCRIPTION
**Pull request by GenericMale**
This fixes the HotMovies scraper.

Note that AdultEmpire provides the same data as HotMovies with a different UI.
The AdultEmpire scraper currently searches for dvds and this HotMovies scraper searches for clips which i feel is a good split.

### CODE REVIEW

**Comment by GenericMale** [comment]
@Maista6969 sorry, i fixed the validation now by getting rid of the javascript seconds to hh:mm:ss conversion

**Comment by Maista6969** [comment]
> @Maista6969 sorry, i fixed the validation now by getting rid of the javascript seconds to hh:mm:ss conversion

Hehe, and I just fixed the validator so you could keep it 🙂 The `javascript` postprocessor is new enough that you're the first one to run into this validation error! You can revert your most recent commit and this should still pass and we can get it merged 👍

**Comment by GenericMale** [comment]
> > @Maista6969 sorry, i fixed the validation now by getting rid of the javascript seconds to hh:mm:ss conversion
> 
> Hehe, and I just fixed the validator so you could keep it 🙂 The `javascript` postprocessor is new enough that you're the first one to run into this validation error! You can revert your most recent commit and this should still pass and we can get it merged 👍

it's fine this way though. end result is the same. not having some wonky javascript in there feels like a good idea if it can be avoided 😅

**Comment by Maista6969** [comment]
Good point, there's too much javascript in the world as is 😁

**Pull request merged**
