### PR TITLE
Clips4sale fix

### PR DESCRIPTION
**Pull request by bnkai**
A quick fix, needs testing with more scens/studios
I removed the `performers` since i couldnt find scenes with the performers in tags as stated in the original scraper.

### CODE REVIEW

**Comment by jb19774** [comment]
tested 4+ studios, lgtm

**Comment by peolic** [comment]
> I removed the `performers` since i couldnt find scenes with the performers in tags as stated in the original scraper.

Please keep the performers. I can confirm there are studios who put performer names as tags.
For example studios `81593` and `67653`.

**Comment by bnkai** [comment]
Readded performers.
@peolic thanks for the samples , i tried to find some before your post but i wasn't lucky.

**Comment by nocrad349** [comment]
Tested 5 studios, 20 clips, everything looks good.

**Pull request merged**
