### PR TITLE
Add JavDB_zh scraper

### PR DESCRIPTION
**Pull request by 8ar10der**
Add a new scraper for gathering Chinese info from javdb.com

### CODE REVIEW

**Comment by feederbox826** [comment]
Closing for the same reason as #1201 as it is just a set cookie

**Comment by 8ar10der** [comment]
Hi @feederbox826 ,

No, it is not easy work to let the script work by just changing the cookies. The element's key names in the Chinese web are totally different, they all will be changed to the Chinese.

If you compare with [javdb.yml](https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/javdb.yml), you will find the answer.

**Comment by feederbox826** [comment]
OK, will try to resolve the differences between the two

**Comment by feederbox826** [comment]
Resolved and merged, I wasn't able to verify all the metadata, please report back

**Pull request closed without merging**
