### PR TITLE
Add xPath scraper for jacquieetmicheltv

### PR DESCRIPTION
**Pull request by niemands**
Requested in #73 
Currently not working, due to cookies not being enabled.
`if(!cookiesEnabled){var q = document.getElementById('no-cookie-warning');`
Using CDP doesn't solve this.

### CODE REVIEW

**Comment by bnkai** [comment]
i was able to scrape a single scene using CDP and appending `?dscl=1` to the scene URL before cloudlfare throwing the hcapta page and blocking me off
adding to #81 till we sort this out

**Comment by niemands** [comment]
The scraper is still not working, even with cdp (javascript required) and cookies set. The site always shows the captcha page.

**Comment by bnkai** [comment]
> The scraper is still not working, even with cdp (javascript required) and cookies set. The site always shows the captcha page.

Yeah thats what happens for me too. With cdp (remote instance) and cookies i only get 1 scene matched and then all subsequent queries are as you mention.

**Comment by killjoy4115** [comment]
I wrote a python [script](https://gist.github.com/killjoy4115/6fec669f04d2a2a6c0a852ecaf5c8de3) to scrape the pages. Feel free to use the code however.

**Comment by bnkai** [comment]
> I wrote a python [script](https://gist.github.com/killjoy4115/6fec669f04d2a2a6c0a852ecaf5c8de3) to scrape the pages. Feel free to use the code however.

This looks interesting. From what i can see it needs requests, cfscrape and lxml? Are you ok it i edit it (if needed) and make a new PR? Or do you want to make it instead?

**Comment by killjoy4115** [comment]
> > I wrote a python [script](https://gist.github.com/killjoy4115/6fec669f04d2a2a6c0a852ecaf5c8de3) to scrape the pages. Feel free to use the code however.
> 
> This looks interesting. From what i can see it needs requests, cfscrape and lxml? Are you ok if i edit it (if needed) and make a new PR? Or do you want to make it instead?

You can have at it. My programming skills are pretty lame. I also tested this again an hour ago and it was blocked. I hope the script can be expanded upon to bypass the cloudflare anti-bot thing.

**Comment by bnkai** [comment]
I tried it a bit and it seems to work.
It might get blocked for once or twice but if i try again later it seems to work again
I modified it a bit
```python
from urllib.parse import urlparse
import sys
import string
import json
import base64
import datetime
import sys

import cfscrape
from lxml import html
import requests


def log(*s):
    print(*s, file=sys.stderr)


def strip_end(text, suffix):
    if suffix and text.endswith(suffix):
        return text[:-len(suffix)]
    return text


frag = json.loads(sys.stdin.read())
if not frag['url']:
    log('No URL entered.')
    ret = {}
    print(json.dumps(ret))
    sys.exit(1)

url = frag["url"]
scraper = cfscrape.create_scraper()
try:
    scraped = scraper.get(url)
except:
    log("scrape error")

if scraped.status_code >= 400:
    log('HTTP Error: %s' % scraped.status_code)

tree = html.fromstring(scraped.content)
title = tree.xpath("//h1/text()")[0]
date = tree.xpath("//span[@class='publication']/text()")[0]
details = tree.xpath("//div[@class='video-description']/p")[0]
tags = tree.xpath("//span[@class='categories']/a/strong/text()")
imgurl = tree.xpath("//video[@id='video-player']/@poster")[0]
img = scraper.get(imgurl).content
b64img = base64.b64encode(img)
datauri = "data:image/jpeg;base64,"

ret = {
    'title': title,
    'tags': [{
        'name': strip_end(x, ", ")
    } for x in tags],
    'date': datetime.datetime.strptime(date, "%m/%d/%Y").strftime("%Y-%m-%d"),
    'details': details.text_content(),
    'image': datauri + b64img.decode('utf-8'),
}

print(json.dumps(ret))
```
In  <https://pypi.org/project/cfscrape/>  it is mentioned that you might need node>=10 installed and also sometimes you might need to increase the delay from the default 5s with something like `scraper = cfscrape.create_scraper(delay=10)` instead of the `scraper = cfscrape.create_scraper()`

**Comment by killjoy4115** [comment]
I'm still getting 403s on pages. I wonder if a sort of plugin workaround could be implemented similar to how [pyLoad](https://github.com/pyload/pyload) handles captchas.

**Comment by bnkai** [comment]
Maybe change the 
```python
if scraped.status_code >= 400:
    log('HTTP Error: %s' % scraped.status_code)
```
to 
```python
if scraped.status_code >= 400:
    log('HTTP Error: %s' % scraped.content)
```
to see whats the actual reason you get 403s?

**Comment by killjoy4115** [comment]
The 403 is caused by the antibot/captcha. If you delete the cookies for the site, you will have to redo the captcha.

**Comment by bnkai** [comment]
The `2` seems a lot more restrictive, i even get adblock disable popup in my browser

**Comment by killjoy4115** [comment]
Everything is working fine now. 👍

**Comment by niemands** [comment]
Good, to hear that. Do you want to make a seperate PR for that? I would close this one then

**Comment by bnkai** [comment]
@niemands made #458. I think we can close this

**Pull request closed without merging**
