### PR TITLE
Add Watch4Beauty gallery/scene URL JSON scraper

### PR DESCRIPTION
**Pull request by n0bodyyouknow**
Required useCDP due to Javascript loading of performer details.
Provided two options for scene image, video preview by default, but can switch to "gallery cover" image if preferred.

### CODE REVIEW

**Comment by n0bodyyouknow** [comment]
Added "CDP" to "Needs" column in scraper list.

**Comment by bnkai** [comment]
It seems that there is a json api we can use instead.
This also gives access to tags

```yaml
name: Watch4Beauty
sceneByURL:
  - action: scrapeJson
    url: 
      - https://www.watch4beauty.com/updates/
    queryURL: https://www.watch4beauty.com/api/{url}
    scraper: sceneScraper
    queryURLReplace:
      url:
        - regex: '.+/updates/'
          with: 'issues/'
galleryByURL:
  - action: scrapeJson
    url:
      - https://www.watch4beauty.com/stories/
    queryURL: https://www.watch4beauty.com/api/{url}
    scraper: galleryStoriesScraper
    queryURLReplace:
      url:
        - regex: '.+/stories/'
          with: 'magazines/'
  - action: scrapeJson
    url:
      - https://www.watch4beauty.com/updates/
    queryURL: https://www.watch4beauty.com/api/{url}
    scraper: galleryUpdatesScraper
    queryURLReplace:
      url:
        - regex: '.+/updates/'
          with: 'issues/'
jsonScrapers:
  sceneScraper:
    scene:
      Title: &updatesTitle 0.issue_title
      Details: &updatesDetails 0.issue_text
      Date: &updatesDate
        selector: 0.issue_datetime
        postProcess:
          - replace:
              - regex: T.+
                with: ""
      Image:
        selector: 0.issue_datetime
        postProcess:
           - replace:
               - regex: T.+
                 with: ""
           - replace:
               - regex: '(\d+)-(\d+)-(\d+)'
                 with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-issue-cover-wide-2560.jpg" # wide cover
                 #with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-issue-cover-640.jpg" # normal cover
      Performers: &updatesPerformers
        Name:
          selector: 0.issue_simple_title
          postProcess:
            - replace:
                - regex: ^
                  with: "https://www.watch4beauty.com/api/issues/"
                - regex: $
                  with: "/models"
            - subScraper:
                selector: "0.Models.#.model_nickname"
                concat: ","
          split: ","
      Studio: &studioAttr
        Name:
          fixed: Watch4Beauty
      Tags: &updatesTags
        Name:
          selector: 0.issue_tags
          split: ", "
  galleryStoriesScraper:
    gallery:
      Title: 0.magazine_title
      Details: 0.magazine_text
      Date:
        selector: 0.magazine_datetime
        postProcess:
          - replace:
              - regex: T.+
                with: ""
      Performers:
        Name:
          selector: 0.magazine_simple_title
          postProcess:
            - replace:
                - regex: ^
                  with: "https://www.watch4beauty.com/api/magazines/"
                - regex: $
                  with: "/models"
            - subScraper:
                selector: "0.Models.#.model_nickname"
                concat: ","
            
          split: ","
      Studio: *studioAttr
      Tags:
        Name:
          selector: 0.magazine_tags
          split: ", "
  galleryUpdatesScraper:
    gallery:
      Title: *updatesTitle
      Details: *updatesDetails
      Performers: *updatesPerformers
      Date: *updatesDate
      Studio: *studioAttr
      Tags: *updatesTags
# Last Updated November 12, 2021

```

An extra note `stories` are plain galleries while `updates` seem to be videos + galleries or plain videos, thats why the scraper needs to have two separate sections for the galley part

**Comment by n0bodyyouknow** [comment]
Nice, get to learn something else new. For future reference, how are you able to determine that a JSON API was available on this site?

**Comment by n0bodyyouknow** [comment]
It seems like at least some `/stories/` URLs do include both video + gallery (e.g. `https://www.watch4beauty.com/stories/tropical-paradise`) so I guess we would want to support both URLs for scenes and galleries?

**Comment by n0bodyyouknow** [comment]
How's this look?  Seems to work for me.

```name: Watch4Beauty
sceneByURL:
  - action: scrapeJson
    url: &storiesURL
      - https://www.watch4beauty.com/stories/
    queryURL: https://www.watch4beauty.com/api/{url}
    scraper: sceneStoriesScraper
    queryURLReplace:
      url:
        - regex: '.+/stories/'
          with: 'magazines/'
  - action: scrapeJson
    url: &updatesURL
      - https://www.watch4beauty.com/updates/
    queryURL: https://www.watch4beauty.com/api/{url}
    scraper: sceneUpdatesScraper
    queryURLReplace:
      url:
        - regex: '.+/updates/'
          with: 'issues/'
galleryByURL:
  - action: scrapeJson
    url: *storiesURL
    queryURL: https://www.watch4beauty.com/api/{url}
    scraper: galleryStoriesScraper
    queryURLReplace:
      url:
        - regex: '.+/stories/'
          with: 'magazines/'
  - action: scrapeJson
    url: *updatesURL
    queryURL: https://www.watch4beauty.com/api/{url}
    scraper: galleryUpdatesScraper
    queryURLReplace:
      url:
        - regex: '.+/updates/'
          with: 'issues/'
jsonScrapers:
  sceneStoriesScraper:
    scene:
      Title: &storiesTitle 0.magazine_title
      Details: &storiesDetails 0.magazine_text
      Date: &storiesDate
        selector: 0.magazine_datetime
        postProcess:
          - replace:
              - regex: T.+
                with: ""
      Image: &storiesImage
        selector: 0.magazine_datetime
        postProcess:
           - replace:
               - regex: T.+
                 with: ""
           - replace:
               - regex: '(\d+)-(\d+)-(\d+)'
                 with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-magazine-cover-wide-2560.jpg" # wide cover
                 #with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-magazine-cover-640.jpg" # normal cover
      Performers: &storiesPerformers
        Name:
          selector: 0.magazine_simple_title
          postProcess:
            - replace:
                - regex: ^
                  with: "https://www.watch4beauty.com/api/magazines/"
                - regex: $
                  with: "/models"
            - subScraper:
                selector: "0.Models.#.model_nickname"
                concat: ","
            
          split: ","
      Studio: &studioAttr
        Name:
          fixed: Watch4Beauty
      Tags: &storiesTags
        Name:
          selector: 0.magazine_tags
          split: ", "
  sceneUpdatesScraper:
    scene:
      Title: &updatesTitle 0.issue_title
      Details: &updatesDetails 0.issue_text
      Date: &updatesDate
        selector: 0.issue_datetime
        postProcess:
          - replace:
              - regex: T.+
                with: ""
      Image:
        selector: 0.issue_datetime
        postProcess:
           - replace:
               - regex: T.+
                 with: ""
           - replace:
               - regex: '(\d+)-(\d+)-(\d+)'
                 with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-issue-cover-wide-2560.jpg" # wide cover
                 #with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-issue-cover-640.jpg" # normal cover
      Performers: &updatesPerformers
        Name:
          selector: 0.issue_simple_title
          postProcess:
            - replace:
                - regex: ^
                  with: "https://www.watch4beauty.com/api/issues/"
                - regex: $
                  with: "/models"
            - subScraper:
                selector: "0.Models.#.model_nickname"
                concat: ","
          split: ","
      Studio: *studioAttr
      Tags: &updatesTags
        Name:
          selector: 0.issue_tags
          split: ", "
  galleryStoriesScraper:
    gallery:
      Title: *storiesTitle
      Details: *storiesDetails
      Date: *storiesDate
      Performers: *storiesPerformers
      Studio: *studioAttr
      Tags: *storiesTags
  galleryUpdatesScraper:
    gallery:
      Title: *updatesTitle
      Details: *updatesDetails
      Performers: *updatesPerformers
      Date: *updatesDate
      Studio: *studioAttr
      Tags: *updatesTags
# Last Updated November 12, 2021
```

**Comment by bnkai** [comment]
Yeah thas almost the same with what i would do
```yaml
name: Watch4Beauty
sceneByURL:
  - action: scrapeJson
    url: &urlUpdates
      - https://www.watch4beauty.com/updates/
    queryURL: &query https://www.watch4beauty.com/api/{url}
    scraper: sceneScraper
    queryURLReplace: &queryUpdates
      url:
        - regex: '.+/updates/'
          with: 'issues/'
  - action: scrapeJson
    url: &urlStories
      - https://www.watch4beauty.com/stories/
    queryURL: *query
    scraper: sceneStoriesScraper
    queryURLReplace: &queryStories
      url:
        - regex: '.+/stories/'
          with: 'magazines/'
galleryByURL:
  - action: scrapeJson
    url: *urlStories
    queryURL: *query
    scraper: galleryStoriesScraper
    queryURLReplace: *queryStories
  - action: scrapeJson
    url: *urlUpdates
    queryURL: *query
    scraper: galleryUpdatesScraper
    queryURLReplace: *queryUpdates

jsonScrapers:
  sceneScraper:
    scene:
      Title: &updatesTitle 0.issue_title
      Details: &updatesDetails 0.issue_text
      Date: &updatesDate
        selector: 0.issue_datetime
        postProcess:
          - replace:
              - regex: T.+
                with: ""
      Image:
        selector: 0.issue_datetime
        postProcess:
           - replace:
               - regex: T.+
                 with: ""
           - replace:
               - regex: '(\d+)-(\d+)-(\d+)'
                 with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-issue-cover-wide-2560.jpg" # wide cover
                 #with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-issue-cover-640.jpg" # normal cover
      Performers: &updatesPerformers
        Name:
          selector: 0.issue_simple_title
          postProcess:
            - replace:
                - regex: ^
                  with: "https://www.watch4beauty.com/api/issues/"
                - regex: $
                  with: "/models"
            - subScraper:
                selector: "0.Models.#.model_nickname"
                concat: ","
          split: ","
      Studio: &studioAttr
        Name:
          fixed: Watch4Beauty
      Tags: &updatesTags
        Name:
          selector: 0.issue_tags
          split: ", "
  sceneStoriesScraper:
    scene:
      Title: &storiesTitle 0.magazine_title
      Details: &storiesDetails 0.magazine_text
      Date: &storiesDate
        selector: 0.magazine_datetime
        postProcess:
          - replace:
              - regex: T.+
                with: ""
      Image:
        selector: 0.magazine_datetime
        postProcess:
           - replace:
               - regex: T.+
                 with: ""
           - replace:
               - regex: '(\d+)-(\d+)-(\d+)'
                 with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-magazine-cover-wide-2560.jpg" # wide cover
                 #with: "https://s5q3w2t8.ssl.hwcdn.net/production/$1$2$3-magazine-cover-640.jpg" # normal cover
      Performers: &storiesPerformers
        Name:
          selector: 0.magazine_simple_title
          postProcess:
            - replace:
                - regex: ^
                  with: "https://www.watch4beauty.com/api/magazines/"
                - regex: $
                  with: "/models"
            - subScraper:
                selector: "0.Models.#.model_nickname"
                concat: ","
          split: ","
      Studio: &studioAttr
        Name:
          fixed: Watch4Beauty
      Tags: &storiesTags
        Name:
          selector: 0.magazine_tags
          split: ", "
  galleryStoriesScraper:
    gallery:
      Title: *storiesTitle
      Details: *storiesDetails
      Date: *storiesDate
      Performers: *storiesPerformers
      Studio: *studioAttr
      Tags: *storiesTags
  galleryUpdatesScraper:
    gallery:
      Title: *updatesTitle
      Details: *updatesDetails
      Performers: *updatesPerformers
      Date: *updatesDate
      Studio: *studioAttr
      Tags: *updatesTags
# Last Updated November 12, 2021
```



> Nice, get to learn something else new. For future reference, how are you able to determine that a JSON API was available on this site?

If you go to the scene/gallery page and hit F12(or the equivalent for the dev tools mode) on the browser you can have a look at the network tab. If you spot some json files and the contents look ok then you can start looking for the api endpoint that gives the scenes/models/tags .... and so on. In this case there was one for stories and one for updates

**Comment by n0bodyyouknow** [comment]
Just realized the original xPath Watch4Beauty.yml was not under the scrapers folder.  Deleted it and added the new JSON based version in the proper location.

**Pull request merged**
