### PR TITLE
Local ComicInfo.xml file

### PR DESCRIPTION
**Pull request by NozomiClambie**
No idea if this belongs here or in another repo as it is a local XML file scraper rather than a site scraper so feel free to redirect me to the right place!

### CODE REVIEW

**Comment by bnkai** [comment]
I used the existing `py_common` code to use graphql for the gallery path 
and pathlib.Path to hopefully get a scraper that works for all os

the `graphql.py` file in `py_common` needs to be updated for the gallery query
```py
import requests

import py_common.config as config
import py_common.log as log


def callGraphQL(query, variables=None):
    api_key = ""
    if config.STASH.get("api_key"):
        api_key = config.STASH["api_key"]

    if config.STASH.get("url") is None:
        log.error("You need to set the URL in 'config.py'")
        return None

    stash_url = config.STASH["url"] + "/graphql"
    headers = {
        "Accept-Encoding": "gzip, deflate, br",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Connection": "keep-alive",
        "DNT": "1",
        "ApiKey": api_key
    }
    json = {
        'query': query
    }
    if variables is not None:
        json['variables'] = variables
    try:
        response = requests.post(stash_url, json=json, headers=headers)
        if response.status_code == 200:
            result = response.json()
            if result.get("error"):
                for error in result["error"]["errors"]:
                    raise Exception("GraphQL error: {}".format(error))
            if result.get("data"):
                return result.get("data")
        elif response.status_code == 401:
            log.debug("[ERROR][GraphQL] HTTP Error 401, Unauthorised.")
            return None
        else:
            raise ConnectionError(
                "GraphQL query failed:{} - {}".format(response.status_code, response.content))
    except Exception as err:
        log.debug(err)
        return None


def configuration():
    query = """
    query Configuration {
        configuration {
            ...ConfigData
        }
    }
    fragment ConfigData on ConfigResult {
        general {
            ...ConfigGeneralData
        }
        interface {
            ...ConfigInterfaceData
        }
        dlna {
            ...ConfigDLNAData
        }
        scraping {
            ...ConfigScrapingData
        }
        defaults {
            ...ConfigDefaultSettingsData
        }
    }
    fragment ConfigGeneralData on ConfigGeneralResult {
        stashes {
            path
            excludeVideo
            excludeImage
        }
        databasePath
        generatedPath
        metadataPath
        cachePath
        calculateMD5
        videoFileNamingAlgorithm
        parallelTasks
        previewAudio
        previewSegments
        previewSegmentDuration
        previewExcludeStart
        previewExcludeEnd
        previewPreset
        maxTranscodeSize
        maxStreamingTranscodeSize
        writeImageThumbnails
        apiKey
        username
        password
        maxSessionAge
        trustedProxies
        logFile
        logOut
        logLevel
        logAccess
        createGalleriesFromFolders
        videoExtensions
        imageExtensions
        galleryExtensions
        excludes
        imageExcludes
        customPerformerImageLocation
        scraperUserAgent
        scraperCertCheck
        scraperCDPPath
        stashBoxes {
            name
            endpoint
            api_key
        }
    }
    fragment ConfigInterfaceData on ConfigInterfaceResult {
        menuItems
        soundOnPreview
        wallShowTitle
        wallPlayback
        maximumLoopDuration
        noBrowser
        autostartVideo
        autostartVideoOnPlaySelected
        continuePlaylistDefault
        showStudioAsText
        css
        cssEnabled
        language
        slideshowDelay
        disabledDropdownCreate {
            performer
            tag
            studio
        }
        handyKey
        funscriptOffset
    }
    fragment ConfigDLNAData on ConfigDLNAResult {
        serverName
        enabled
        whitelistedIPs
        interfaces
    }
    fragment ConfigScrapingData on ConfigScrapingResult {
        scraperUserAgent
        scraperCertCheck
        scraperCDPPath
        excludeTagPatterns
    }
    fragment ConfigDefaultSettingsData on ConfigDefaultSettingsResult {
        scan {
            useFileMetadata
            stripFileExtension
            scanGeneratePreviews
            scanGenerateImagePreviews
            scanGenerateSprites
            scanGeneratePhashes
            scanGenerateThumbnails
        }
        identify {
            sources {
                source {
                    ...ScraperSourceData
                }
                options {
                    ...IdentifyMetadataOptionsData
                }
            }
            options {
                ...IdentifyMetadataOptionsData
            }
        }
        autoTag {
            performers
            studios
            tags
            __typename
        }
        generate {
            sprites
            previews
            imagePreviews
            previewOptions {
                previewSegments
                previewSegmentDuration
                previewExcludeStart
                previewExcludeEnd
                previewPreset
            }
            markers
            markerImagePreviews
            markerScreenshots
            transcodes
            phashes
        }
        deleteFile
        deleteGenerated
    }
    fragment ScraperSourceData on ScraperSource {
        stash_box_index
        stash_box_endpoint
        scraper_id
    }
    fragment IdentifyMetadataOptionsData on IdentifyMetadataOptions {
        fieldOptions {
            ...IdentifyFieldOptionsData
        }
        setCoverImage
        setOrganized
        includeMalePerformers
    }
    fragment IdentifyFieldOptionsData on IdentifyFieldOptions {
        field
        strategy
        createMissing
    }
    """
    result = callGraphQL(query)
    if result:
        return result.get("configuration")
    return None


def getScene(scene_id):
    query = """
    query FindScene($id: ID!, $checksum: String) {
        findScene(id: $id, checksum: $checksum) {
            ...SceneData
        }
    }
    fragment SceneData on Scene {
        id
        checksum
        oshash
        title
        details
        url
        date
        rating
        o_counter
        organized
        path
        phash
        interactive
        file {
            size
            duration
            video_codec
            audio_codec
            width
            height
            framerate
            bitrate
        }
        paths {
            screenshot
            preview
            stream
            webp
            vtt
            chapters_vtt
            sprite
            funscript
        }
        scene_markers {
            ...SceneMarkerData
        }
        galleries {
            ...SlimGalleryData
        }
        studio {
            ...SlimStudioData
        }
        movies {
            movie {
                ...MovieData
            }
            scene_index
        }
        tags {
            ...SlimTagData
        }
        performers {
            ...PerformerData
        }
        stash_ids {
            endpoint
            stash_id
        }
    }
    fragment SceneMarkerData on SceneMarker {
        id
        title
        seconds
        stream
        preview
        screenshot
        scene {
            id
        }
        primary_tag {
            id
            name
            aliases
        }
        tags {
            id
            name
            aliases
        }
    }
    fragment SlimGalleryData on Gallery {
        id
        checksum
        path
        title
        date
        url
        details
        rating
        organized
        image_count
        cover {
            file {
                size
                width
                height
            }
            paths {
                thumbnail
            }
        }
        studio {
            id
            name
            image_path
        }
        tags {
            id
            name
        }
        performers {
            id
            name
            gender
            favorite
            image_path
        }
        scenes {
            id
            title
            path
        }
    }
    fragment SlimStudioData on Studio {
        id
        name
        image_path
        stash_ids {
            endpoint
            stash_id
        }
        parent_studio {
            id
        }
        details
        rating
        aliases
    }
    fragment MovieData on Movie {
        id
        checksum
        name
        aliases
        duration
        date
        rating
        director
        studio {
            ...SlimStudioData
        }
        synopsis
        url
        front_image_path
        back_image_path
        scene_count
        scenes {
            id
            title
            path
        }
    }
    fragment SlimTagData on Tag {
        id
        name
        aliases
        image_path
    }
    fragment PerformerData on Performer {
        id
        checksum
        name
        url
        gender
        twitter
        instagram
        birthdate
        ethnicity
        country
        eye_color
        height
        measurements
        fake_tits
        career_length
        tattoos
        piercings
        aliases
        favorite
        image_path
        scene_count
        image_count
        gallery_count
        movie_count
        tags {
            ...SlimTagData
        }
        stash_ids {
            stash_id
            endpoint
        }
        rating
        details
        death_date
        hair_color
        weight
    }
    """
    variables = {
        "id": scene_id
    }
    result = callGraphQL(query, variables)
    if result:
        return result.get('findScene')
    return None

def getGallery(gallery_id):
    query = """
    query FindGallery($id: ID!) {
        findGallery(id: $id) {
            ...GalleryData
        }
    }
    fragment GalleryData on Gallery {
        id
        checksum
        path
        created_at
        updated_at
        title
        date
        url
        details
        rating
        organized
        images {
            ...SlimImageData
        }
        cover {
            ...SlimImageData
        }
        studio {
            ...SlimStudioData
        }
        tags {
            ...SlimTagData
        }

        performers {
            ...PerformerData
        }
        scenes {
            ...SlimSceneData
        }
    }
    fragment SlimImageData on Image {
        id
        checksum
        title
        rating
        organized
        o_counter
        path

        file {
            size
            width
            height
            }

        paths {
            thumbnail
            image
            }

        galleries {
            id
            path
            title
            }

        studio {
            id
            name
            image_path
            }

        tags {
            id
            name
            }

        performers {
            id
            name
            gender
            favorite
            image_path
            }
    }
    fragment SlimStudioData on Studio {
        id
        name
        image_path
        stash_ids {
        endpoint
        stash_id
        }
        parent_studio {
            id
        }
        details
        rating
        aliases
    }
    fragment SlimTagData on Tag {
        id
        name
        aliases
        image_path
        }
    fragment PerformerData on Performer {
        id
        checksum
        name
        url
        gender
        twitter
        instagram
        birthdate
        ethnicity
        country
        eye_color
        height
        measurements
        fake_tits
        career_length
        tattoos
        piercings
        aliases
        favorite
        image_path
        scene_count
        image_count
        gallery_count
        movie_count

        tags {
        ...SlimTagData
        }

        stash_ids {
        stash_id
        endpoint
        }
        rating
        details
        death_date
        hair_color
        weight
    }
    fragment SlimSceneData on Scene {
        id
        checksum
        oshash
        title
        details
        url
        date
        rating
        o_counter
        organized
        path
        phash
        interactive
        interactive_speed

        file {
            size
            duration
            video_codec
            audio_codec
            width
            height
            framerate
            bitrate
        }

        paths {
            screenshot
            preview
            stream
            webp
            vtt
            chapters_vtt
            sprite
            funscript
            interactive_heatmap
        }

        scene_markers {
            id
            title
            seconds
            }

        galleries {
            id
            path
            title
        }

        studio {
            id
            name
            image_path
        }

        movies {
            movie {
            id
            name
            front_image_path
            }
            scene_index
        }

        tags {
            id
            name
            }

        performers {
            id
            name
            gender
            favorite
            image_path
        }

        stash_ids {
            endpoint
            stash_id
        }
    }


    """
    variables = {
        "id": gallery_id
    }
    result = callGraphQL(query, variables)
    if result:
        return result.get('findGallery')
    return None 
```
and the updated `ComicInfoXML.py`
```py
import os
import sys
import json
import sqlite3
import mimetypes
import base64
import xml.etree.ElementTree as ET
import pathlib

import py_common.graphql as graphql
import py_common.log as log

"""
This script parses xml files for metadata. 
The .xml file must be in the same directory as the gallery files and named either ComicInfo.xml for loose files (folder full oj jpg/png's) 
or the same name as the .cbz/.zip file
"""
def query_xml(gallery_path, title):
    res={"title":title}
    try:
        tree=ET.parse(gallery_path)
    except Exception as e:
        log.error(f'xml parsing failed:{e}')
        print(json.dumps(res))
        exit(1)
    
    if tree.find("Title") != None:
        res["title"] = tree.find("Title").text

    if tree.find("Web") != None:
        res["url"] = tree.find("Web").text

    if tree.find("Summary") != None:
        res["details"] = tree.find("Summary").text

    if tree.find("Released") != None:
        res["date"] = tree.find("Released").text
    
    if tree.find("Genre") != None:
        if tree.find("Genre").text:
            new_tags = [t for x in tree.findall("Genre") for t in x.text.split(", ")]
            if "tags" in res:
                res["tags"] += [{"name":x} for x in new_tags]
            else:
                res["tags"] = [{"name":x} for x in new_tags]

    if tree.find("Writer") != None:
        if tree.find("Writer").text:
            res["studio"] = {"name":tree.find("Writer").text}

    return res


if sys.argv[1] == "query":
    fragment = json.loads(sys.stdin.read())
    g_id = fragment.get("id")
    if not g_id:
        log.error(f"No ID found")
        sys.exit(1)

    gallery = graphql.getGallery(g_id)
    if gallery:
        gallery_path = gallery.get("path")
        if gallery_path:
            p = pathlib.Path(gallery_path)
            
            res = {"title": fragment["title"]}
            # Check for an xml file that exists in the same folder with the same name as the .cbz or .zip
            if "cbz" in gallery_path:
                 # Look for filename.xml where filename.cbz is the gallery
                 f = p.with_suffix('.xml')
                 log.debug(f"CBZ Format, using: {f}")
            elif "zip" in gallery_path:
                # Look for filename.xml where filename.zip is the gallery
                f = p.with_suffix('.xml')
                log.debug(f"ZIP Format, using:{f}")
            else:
                # Use loose files format
                # Look for ComicInfo.xml in the gallery's folder
                f = pathlib.Path(p.parent.resolve(),"ComicInfo.xml")
                log.debug(f"Folder format, using:{f}")

            if f.is_file():
                res = query_xml(f, fragment["title"])
            else:
                log.warning(f'No file found: {f}')

            print(json.dumps(res))
            exit(0)
```
All the user has to do is edit the `py_common` config.py 

I didnt test any actual sample files  and the problematic one still fails but thats because its not a valid xml file (added a try when parsing the file)

**Comment by NozomiClambie** [comment]
Unfortunately appears to be failing :(
```
2021-12-27 11:08:34 Debug   Scraper script <python3 ComicInfoXML.py query gallery> started
2021-12-27 11:08:35 Debug   [Scrape / ComicInfo XML] 5592
2021-12-27 11:08:35 Debug   [Scrape / ComicInfo XML] GraphQL query failed:422 - b'{"errors":[{"message":"Cannot query field \\"interactive_speed\\" on type \\"Scene\\". Did you mean \\"interactive\\"?","locations":[{"line":159,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"interactive_heatmap\\" on type \\"ScenePathsType\\".","locations":[{"line":181,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"interactive_speed\\" on type \\"Scene\\". Did you mean \\"interactive\\"?","locations":[{"line":159,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"interactive_heatmap\\" on type \\"ScenePathsType\\".","locations":[{"line":181,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"interactive_speed\\" on type \\"Scene\\". Did you mean \\"interactive\\"?","locations":[{"line":159,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \\"interactive_heatmap\\" on type \\"ScenePathsType\\".","locations":[{"line":181,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}'
2021-12-27 11:08:35 Error   could not unmarshal json: EOF
```

Here's a SFW Sample file that shouldn't fail due to any special characters
```xml
<?xml version="1.0"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Title>Versatile Mage</Title>
  <Series></Series>
  <Summary>Summary:
He awoke, and the world was changed. The familiar high school now teaches magic, encouraging students to become the greatest magicians they can be. Beyond the city limits, wandering magical beasts prey on humans.

An advanced scientific world changed into one with advanced magic. Yet, what has not changed was the same teacher who looks upon him with disdain, the same students who look upon him with contempt, the same father who struggles at the bottom rung of society, and the same innocent step sister who cannot walk.

However, Mo Fan discovered that while everyone else can only use one major element, he himself can use all magic!</Summary>
  <Writer>Chaos</Writer>
  <Penciller>Penciller Placeholder</Penciller>
  <Inker>Inker Placeholder</Inker>
  <Letterer>Letterer Placeholder</Letterer>
  <CoverArtist>Chaos</CoverArtist>
  <Editor>Editor Placeholder</Editor>
  <Publisher>Publisher Placeholder</Publisher>
  <Genre>Action, Adventure, Drama, Fantasy, Martial Arts, School Life, Supernatural, Tragedy</Genre>
  <Web>https://readmanganato.com/manga-bf979214</Web>
  <LanguageISO>en</LanguageISO>
  <Translator></Translator>
  <AgeRating></AgeRating>
  <Manga>Yes</Manga>
  <Characters></Characters>
  <PageCount>633</PageCount>
  <Pages>
    <Page Image="0" ImageSize="160056" ImageWidth="800" ImageHeight="1244" Key="Versatile Mage (Original)\Chapter 44_443.jpg" />
    <Page Image="1" ImageSize="194210" ImageWidth="800" ImageHeight="1135" Key="Versatile Mage (Original)\Chapter 1_00.jpg" />
    <Page Image="2" ImageSize="165734" ImageWidth="800" ImageHeight="1228" Key="Versatile Mage (Original)\Chapter 32_331.jpg" />
    <Page Image="3" ImageSize="148363" ImageWidth="800" ImageHeight="1176" Key="Versatile Mage (Original)\Chapter 62_612.jpg" />
    <Page Image="4" ImageSize="176644" ImageWidth="800" ImageHeight="1184" Key="Versatile Mage (Original)\Chapter 26_266.jpg" />
  </Pages>
</ComicInfo>
```

**Comment by NozomiClambie** [comment]
This works for loose folder format:
```py
    gallery = graphql.getGallery(g_id)
    if gallery:
        gallery_path = gallery.get("path")
        if gallery_path:
            p = pathlib.Path(gallery_path)
            
            res = {"title": fragment["title"]}
            # Check for an xml file that exists in the same folder with the same name as the .cbz or .zip
            if "cbz" in gallery_path:
                 # Look for filename.xml where filename.cbz is the gallery
                 f = p.with_suffix('.xml')
                 log.debug(f"CBZ Format, using: {f}")
            elif "zip" in gallery_path:
                # Look for filename.xml where filename.zip is the gallery
                f = p.with_suffix('.xml')
                log.debug(f"ZIP Format, using:{f}")
            else:
                # Use loose files format
                # Look for ComicInfo.xml in the gallery's folder
                from pathlib import Path
                d = p
                f = Path.joinpath(d, "ComicInfo.xml")
                log.debug(f"Folder format, using:{f}")
```

Is there a better way of doing that?

**Comment by bnkai** [comment]
I forgot to mention that I took the graphql queries from the dev version so you would need that. Just removing the interactive like you did is enough. Tbf I should make a new getGalleryPath that only requests the path since nothing else is needed.

For the loose folder
'f = pathlib.Path(p.resolve(),"ComicInfo.xml")' or the join you used should be ok.

For problematic files I would first open and read the file ( instead of ET.parse) and use regex to replace reserved chars with their escaped ones. I would then feed that as a string to ET. Is it in many fields or just the title?

**Comment by NozomiClambie** [comment]
> Is it in many fields or just the title?

It depends, I have a surprisingly small sample considering the amount of galleries I have (I only had about 15 or so out of around 10,000 xml files that even contained a `&` so it's not very common) but generally speaking, it is usually in the title

When it's in the title, then it's (probably, based on user configuration at least) guaranteed to be in multiple fields due to the way it's generated 
The software by default creates a folder based on the title to download the manga into which it then uses that folder name later on in the XML for every page that exists in said manga
So as an example if I were to use the above again
`/Manga/Versatile Mage/ComicInfo.xml`
```xml
  <Title>Versatile Mage</Title>
  <PageCount>633</PageCount>
  <Pages>
    <Page Image="0" ImageSize="160056" ImageWidth="800" ImageHeight="1244" Key="Versatile Mage (Original)\Chapter 44_443.jpg" />
    <Page Image="1" ImageSize="194210" ImageWidth="800" ImageHeight="1135" Key="Versatile Mage (Original)\Chapter 1_00.jpg" />
    <Page Image="2" ImageSize="165734" ImageWidth="800" ImageHeight="1228" Key="Versatile Mage (Original)\Chapter 32_331.jpg" />
    <Page Image="3" ImageSize="148363" ImageWidth="800" ImageHeight="1176" Key="Versatile Mage (Original)\Chapter 62_612.jpg" />
    <Page Image="4" ImageSize="176644" ImageWidth="800" ImageHeight="1184" Key="Versatile Mage (Original)\Chapter 26_266.jpg" />
  </Pages>
```
`/Manga/Versatile & Mage/ComicInfo.xml`
```xml
  <Title>Versatile & Mage</Title>
  <PageCount>633</PageCount>
  <Pages>
    <Page Image="0" ImageSize="160056" ImageWidth="800" ImageHeight="1244" Key="Versatile & Mage (Original)\Chapter 44_443.jpg" />
    <Page Image="1" ImageSize="194210" ImageWidth="800" ImageHeight="1135" Key="Versatile & Mage (Original)\Chapter 1_00.jpg" />
    <Page Image="2" ImageSize="165734" ImageWidth="800" ImageHeight="1228" Key="Versatile & Mage (Original)\Chapter 32_331.jpg" />
    <Page Image="3" ImageSize="148363" ImageWidth="800" ImageHeight="1176" Key="Versatile & Mage (Original)\Chapter 62_612.jpg" />
    <Page Image="4" ImageSize="176644" ImageWidth="800" ImageHeight="1184" Key="Versatile & Mage (Original)\Chapter 26_266.jpg" />
  </Pages>
```


There were about 2 or 3 files that only had a special character in the plot/summary

I ended up just doing something along the lines of `grep -rl ' & ' /mnt/Manga/*/*.xml | xargs -0 sed -i 's/ & / \&amp; /g'`
I was looking into doing exactly as you suggested, opening and using regex to sanitize it first but considering how few cases there was of a special character I ended up deciding it wasn't really worth the time for me to follow up on the idea as, really, the XML should have been generated correctly from the source in the first place (and i've already reached out to the dev asking to make sure special characters get escaped properly in the xml generation process)

**Comment by bnkai** [comment]
a small update 
we can add a simpler graphql query to the `graphql.py` since we only need the path, the other should stay as a reference
```py
def getGalleryPath(gallery_id):
    query = """
    query FindGallery($id: ID!) {
        findGallery(id: $id) {
            path
        }
    }
        """
    variables = {
        "id": gallery_id
    }
    result = callGraphQL(query, variables)
    if result:
        return result.get('findGallery')
    return None 
```
then in the scraper py file you just need to switch the `graphql.getGallery` to `graphql.getGalleryPath`

**Comment by NozomiClambie** [comment]
Oh yeah, nice that makes sense as we definitely don't need all that other info from the getGallery query for this particular scraper but leaving it there for future reference sounds like a smart idea!

I've since added performers (or in this case, "characters") so I'll submit both those changes after some sleep
```py    
    if tree.find("Characters") != None:
        if tree.find("Characters").text:
            new_performers = [t for x in tree.findall("Characters") for t in x.text.split(", ")]
            if "performers" in res:
                res["performers"] += [{"name":x.title()} for x in new_performers]
            else:
                res["performers"] = [{"name":x.title()} for x in new_performers]
```
Decided to Title Case the performers as they always seems to be lowercase from any site I get it from lol 
Not sure if that's a HDoujinDownloader thing or what but it was bugging me 

The other thing I am interested in doing is making use of the `<Series></Series>` info but there's nowhere to really put it that makes a lot of sense right now, so I opened a [stash feature request](https://github.com/stashapp/stash/issues/2168) and I'll leave this here for now so I remember to follow up on it tomorrow. Thoughts on this idea are welcome!
```py
    # Need to find a suitable spot for this, maybe convert it to and append it as a Tag as something like "Parody: Series Name"
    # Unless galleries get some kind of "Collection/Series" functionality? Which would be more ideal than messying tags
    # if tree.find("Series") != None:
    #     res["movie"] = tree.find("Series").text
```

**Comment by bnkai** [comment]
Only thing I can think of for now is either add it as a tag or append it to the details/description

**Comment by NozomiClambie** [comment]
Yeah that's all I've been able to really come up with as well since I brought it up

After thinking on it for a while I was going to append it to the Details section as I really didn't want my tags to explode (doing this will easily add around about 1000 new "`Series/Parody: x`" tags I think based on my current collection) lol

But then I figured that tags are probably the best option right now as, if the feature request of getting an extra "Series" field added to galleries I submitted is introduced, we can at least bulk delete the tags with a few clicks to clean it up.
Cleaning the details would be much more of a pain I think

**Comment by bnkai** [comment]
@NozomiClambie is the scraper ok for merge or do you need to adjust anything else ?

**Comment by NozomiClambie** [comment]
All good to merge now! I won't be making any more changes to it until there's a better way to manage the series :)

**Comment by bnkai** [comment]
> All good to merge now! I won't be making any more changes to it until there's a better way to manage the series :)

Will make a last test and merge later today.

**Pull request merged**
