### PR TITLE
Update RealityKingsOL.yml xpath scraper

### PR DESCRIPTION
**Pull request by budislov**
Updated the @class on Title, Name, and Image to reflect changes on the sites.

### CODE REVIEW

**Comment by bnkai** [comment]
I tried avoiding the classes alltogether.
These seem to work for all included sites , need to verify against more samples though

```yaml
      Title: //h1/text()
```
```yaml
      Performers:
        Name: //h1/following-sibling::div//a[contains(@href,"/model")]/text()
```
```yaml
      Image: //img[@alt=""][contains(@src,"poster")]/@src
```

**Comment by budislov** [comment]
I will test out your proposed changes with the samples that I have.

**Comment by bnkai** [comment]
thanks @budislov i checked with some scenes but some more verification is needed

**Comment by budislov** [comment]
@bnkai I've tested this with a bunch of different samples on these various sites with no issues.

**Pull request merged**
