### PR TITLE
Update PaperStreetMedia

### PR DESCRIPTION
**Pull request by peolic**
- [x] Add FosterTapes & DadCrush
- [x] Update Performers selector to fix empty values

### CODE REVIEW

**Comment by bnkai** [comment]
The 2 extra sites seem to work ok.
Just noticed though that due to some js comments in the anchor text we get two extra empty performers for   every  performer entry.
Switching to 
```yaml
      Performers:
        Name: //p[@class="model-name"]/a
```
leaves the "cleaning" to stash and we get the expected number of performers.
I tried a few scenes from every site and it seems to work ok. 
Can we verify that @peolic @halorrr ?

**Comment by peolic** [comment]
@bnkai 
I see what you mean.
I tried a few sites with that change, seems to work fine.

**Comment by halorrr** [comment]
Looks good in my tests too. Small thing but you updated the date number but not the month in the "last updated" section.

**Comment by peolic** [comment]
@halorrr 
Thanks

**Pull request merged**
