### PR TITLE
Update DreamTranny.yml

### PR DESCRIPTION
**Pull request by nymeras**
Corrections to work with site update.

### CODE REVIEW

**Comment by DogmaDragon** [comment]
Verified everything works.

**Comment by nrg101** [comment]
I just tried this with a scene, https://dreamtranny.com/update/840 , and the image scraped is not the cover image of _this_ scene, it is the cover image for the one listed below in the More Scenes section

**Comment by nrg101** [comment]
Here is what works for me to scrape the actual cover image:
```
      Image:
        selector: //video[contains(@class,'video-js')]/@poster
        postProcess:
          - replace:
            - regex: ^
              with: "https://dreamtranny.com"
```

**Comment by nymeras** [comment]
> Here is what works for me to scrape the actual cover image:
> 
> ```
>       Image:
>         selector: //video[contains(@class,'video-js')]/@poster
>         postProcess:
>           - replace:
>             - regex: ^
>               with: "https://dreamtranny.com"
> ```

Nice catch, thank you. The original line worked on some scene pages, but not all. Updated.

**Pull request merged**
