### PR TITLE
Search by scene name added but for some reason the image is not being…

### PR DESCRIPTION
**Pull request by freeagent1384**
… picked up.  From what I can tell the xPath is good but no image appears in my UI.

### CODE REVIEW

**Comment by DogmaDragon** [comment]
It uses JS for LazyLoad so you probably need to use [sub-scraper](https://docs.stashapp.cc/in-app-manual/scraping/scraperdevelopment/#post-processing-options) post-processing.

**Comment by Maista6969** [comment]
Looks like their search hits an API, might be easier to use that directly with a JSON parser instead of the XPath... they return the published date as a UNIX timestamp, but that's supported since stashapp/stash#2817

https://content.vrbangers.com/api/content/v1/search/call%20on%20me

**Comment by freeagent1384** [comment]
> It uses JS for LazyLoad so you probably need to use [sub-scraper](https://docs.stashapp.cc/in-app-manual/scraping/scraperdevelopment/#post-processing-options) post-processing.

I'm not familiar with LazyLoad, I'll read up on it this weekend. @DogmaDragon, do you know of another scraper that has to address a similar issue?

**Comment by freeagent1384** [comment]
> Looks like their search hits an API, might be easier to use that directly with a JSON parser instead of the XPath... they return the published date as a UNIX timestamp, but that's supported since stashapp/stash#2817
> 
> https://content.vrbangers.com/api/content/v1/search/call%20on%20me

Thanks @Maista6969, that definitely is a very viable option. I'm fascinated to know how you knew it was an API? Could be very useful in other scrapers.

**Comment by Maista6969** [comment]
> > Looks like their search hits an API, might be easier to use that directly with a JSON parser instead of the XPath... they return the published date as a UNIX timestamp, but that's supported since [stashapp/stash#2817](https://github.com/stashapp/stash/pull/2817)
> > https://content.vrbangers.com/api/content/v1/search/call%20on%20me
> 
> Thanks @Maista6969, that definitely is a very viable option. I'm fascinated to know how you knew it was an API? Could be very useful in other scrapers.

I ran a search with the Developer Tools open and checked the Network tab: a lot more sites are using APIs these days and I got lucky with this one 😃

Developer Tools

**Pull request closed without merging**
