### PR TITLE
Update MatureNL.yml

### PR DESCRIPTION
**Pull request by 1-gran**
Fix image selector

### CODE REVIEW

**Comment by Maista6969** [comment]
I can't see what this is fixing, could you provide an example URL that won't scrape with the current selector?

**Comment by 1-gran** [comment]
> I can't see what this is fixing, could you provide an example URL that won't scrape with the current selector?

Any URL. Im not sure why, but your code will only fetch the image succesfully once. Then if you scrape another URL it wont work. If I restart the app then it will work again, but only once.
Maybe its just on my end, and theres some weird caching going on, I dont know. I tried on Chrome and Firefox.
My PR fixes the issue for me atleast.

**Comment by Maista6969** [comment]
> > I can't see what this is fixing, could you provide an example URL that won't scrape with the current selector?
> 
> Any URL. Im not sure why, but your code will only fetch the image succesfully once. Then if you scrape another URL it wont work. If I restart the app then it will work again, but only once. Maybe its just on my end, and theres some weird caching going on, I dont know. I tried on Chrome and Firefox. My PR fixes the issue for me atleast.

You are quite right that this is a caching issue with the xpath library that Stash depends on: the PR with a fix [has been merged](https://github.com/stashapp/stash/pull/4126) so this selector (and many others like it) will be fully reliable in the next release

**Comment by 1-gran** [comment]
> > > I can't see what this is fixing, could you provide an example URL that won't scrape with the current selector?
> > 
> > 
> > Any URL. Im not sure why, but your code will only fetch the image succesfully once. Then if you scrape another URL it wont work. If I restart the app then it will work again, but only once. Maybe its just on my end, and theres some weird caching going on, I dont know. I tried on Chrome and Firefox. My PR fixes the issue for me atleast.
> 
> You are quite right that this is a caching issue with the xpath library that Stash depends on: the PR with a fix [has been merged](https://github.com/stashapp/stash/pull/4126) so this selector (and many others like it) will be fully reliable in the next release

Oh, lol. Glad you've found the issue. I will just use my own code locally as a workaround until the next release then.

**Pull request closed without merging**
