### PR TITLE
Update VirtualTaboo.yml, WankzVR.yml and VRHush.yml

### PR DESCRIPTION
**Pull request by philpw99**
Now with scene scraper and movie scraper. Basically all info is successfully extracted.

### CODE REVIEW

**Comment by Belleyy** [comment]
You need to update `SCRAPERS-LIST.md` to add the movie support.

**Comment by philpw99** [comment]
Thank you for letting me know! Alright, it's done. I updated the scrapers list.

**Comment by philpw99** [comment]
I am wondering, is there any issues with my updates? Too many changes at the same time? Or there are problems with my changes? Please let me know, thank you!

**Comment by bnkai** [comment]
> I am wondering, is there any issues with my updates? Too many changes at the same time? Or there are problems with my changes? Please let me know, thank you!

Validation and check of the scrapers is done mostly manually so merging a PR may take a while.
If there is any issue with the scraper someone will reply with the details.

PS I had a small issue with the images part in the WankzVR scraper as i got a 403 error (urls seems ok but wankzvr cdn denies access to downloader) but i am merging since i am not sure if it was only my part.

**Pull request merged**
