### PR TITLE
Add BellesaPlus API scraper

### LINKED ISSUE #1892: Bellesa rewrite
**Scraper name**

Bellesa.yml

**Scraper method**

All URLs are now on bellesaplus.co or bellesa.co

working on a rewrite

### PR DESCRIPTION
**Pull request by feederbox826**
- Removed `bellesafilms.com` and `bellesahouse.com` since they redirect to `https://bellesaplus.co/`
- Explicitly removes support for `bellesa.co` since scenes are delayed and paywalled
- Removed old scrape since it was completely nonfunctional with new UI elements

closes #1892 
related: https://github.com/stashapp/CommunityScrapers/issues/1338#issue-1708737874

### CODE REVIEW

**Comment by feederbox826** [comment]
Adding hardcoded tag conversions...

**Comment by Maista6969** [comment]
This is still in draft but it seems to be working fine, is there anything else you'd like to add before we merge?

**Comment by feederbox826** [comment]
I'm currently going through and rescraping all the BellesaHouse scenes on stashDB and gradually adding in manual tag replacements.

I have hit a plateau with tag replacement where they return some semi-valid tags that don't yet exist, so I think it is ready to merge. I will PR more tag replacements once I'm through with all the scenes but it should be in a more than workable state

**Comment by feederbox826** [comment]
just a disclaimer, this is specifically for BellesaPlus (paid) so it will error on non-plus scenes. This is intentional behaviour. It will also error on redistributions. This also intentional behaviour.

**Comment by feederbox826** [comment]
nevermind they changed their URL format will have to commit LOL

**Pull request merged**
