### PR TITLE
Added ability to scrape pages behind PlayboyPlus paywall

### PR DESCRIPTION
**Pull request by quantumandwoody**
Added ability to scrape pages behind paywall using "pbp-ma.playboy.com" formatted URL.

### CODE REVIEW

**Comment by bnkai** [comment]
Does the url translation work for all galleries  or not?
If it is only for some i think it would be better to add the changes commented out ?

**Comment by quantumandwoody** [comment]
It does work for all galleries. They can be scraped from the public facing pages ([](https://www.playboyplus.com/gallery/kay-lovely-in-expose-yourself)) or behind the paywall ([](https://pbp-ma.playboy.com/gallery/kay-lovely-in-expose-yourself)). The regex just changes what the search URL to the public facing site at search time, but doesn't change the output.

**Comment by FlashSpazzbo** [comment]
Would you be able to add pbp-ma-legacy.playboy.com to this regex swap? I believe it's the exact same content, just different CSS.

Reference:
https://www.playboyplus.com/gallery/kay-lovely-in-expose-yourself
https://pbp-ma.playboy.com/gallery/kay-lovely-in-expose-yourself
https://pbp-ma-legacy.playboy.com/gallery/kay-lovely-in-expose-yourself

**Comment by quantumandwoody** [comment]
@FlashSpazzbo I just created a new pull request via a new branch with an updated regex. In case you don't want to wait, you can try this:

`(?:https://)?((pbp-ma|pbp-ma-legacy).playboy.com)/gallery/([^/]*)(?:/vip)?`

**Pull request merged**
