### PR TITLE
add pansexualx.com and transgressivexxx.com to Algolia_EvilAngel

### PR DESCRIPTION
**Pull request by nrg101**
This adds two sites to the existing Algolia_EvilAngel scraper:

- pansexualx.com
- transgressivexxx.com

Both are sub-studios of [EvilAngel](https://stashdb.org/studios/0f1d8e2c-627e-4d05-a52e-c821b26cab0c) at stashdb.org:

- [PansexualX](https://stashdb.org/studios/daee68aa-5261-4bac-af6d-e04998b78704)
- [TransgressiveXXX](https://stashdb.org/studios/45a72078-08f9-4707-8b91-02c27ebf8a99)

### Note on `galleryByURL`

You can use the corresponding scene video URL of a photo set to populate the details for a gallery. It provides all the info including performers, date, tags, title, details/description, and worth adding here even though it doesn't support the more intuitive `DOMAIN/en/photo/` URL pattern of a studio photo set page

### CODE REVIEW

**Comment by nrg101** [comment]
CommunityScrapers-validate-improve-evilangel

**Comment by bnkai** [comment]
>Note on galleryByURL

>You can use the corresponding scene video URL of a photo set to populate the details for a gallery. It provides all the info including performers, date, tags, title, details/description, and worth adding here even though it doesn't support the more intuitive DOMAIN/en/photo/ URL pattern of a studio photo set page

Sites that use the algolia api have a separate query for photosets. Is it worth it to implement a proper gallery support instead?
Some sites have browsable links of the photos while other only join links. Thats the only issue/problen i can think of ( getting the actual urls of the photosets )
For a couple of scenes/photosets i  browsed it seems most meta is indeed the same with some photosets having a description that the scenes lack.

**Comment by nrg101** [comment]
> Sites that use the algolia api have a separate query for photosets.

I couldn't find a `galleryByUrl` example in any of the scrapers that contain "Algolia.py"

> Is it worth it to implement a proper gallery support instead? Some sites have browsable links of the photos while other only join links. Thats the only issue/problen i can think of ( getting the actual urls of the photosets ) For a couple of scenes/photosets i browsed it seems most meta is indeed the same with some photosets having a description that the scenes lack.

Ahh... yeah, I think the EvilAngel photo pages are good enough on consistency and populated data to work with just an xPath scraper for `galleryByUrl`... I'll look at adding that

**Comment by bnkai** [comment]
>or were you suggesting add a photo/gallery query function to the Algolia.py script?

yes that was what i meant, sorry
can you try the Algolia.py version i pasted in #1200?

**Comment by nrg101** [comment]
> can you try the Algolia.py version i pasted in #1200?

there is a publicly accessible https://www.transgressivexxx.com/en/photos with galleries listed so I could confirm the updated Algolia.py with gallery scraper works for that domain, and have modified this file in #1200 instead, for the updated script dependency

**Pull request merged**
