### PR TITLE
Update Femjoy.yml

### PR DESCRIPTION
**Pull request by DogmaDragon**
From https://github.com/stashapp/CommunityScrapers/pull/1107#discussion_r994139923

The site released a new design, the old scraper is broken.

### CODE REVIEW

**Comment by bnkai** [comment]
For the image part i was experimenting with
```yaml
      Image:
        selector: //div[@class='post_details']/h1[@class='post_title']/span/text()
        postProcess:
          - replace:
              - regex: \s
                with: "%2b" # works better than adding plain + or %20
              - regex: ^
                with: "https://www.femjoy.com/videos?s="
          - subScraper: //img[@class="_image item_cover"]/@src
```
It works in most scenes i tried, the problem is if it fails we might end up with a wrong image. Is it worth it ( should we add it commented out by default ?)

**Comment by DogmaDragon** [comment]
I did some checking and almost all single-word titles don't return it as a first result in a search (even if it's an exact match), so the cover would be incorrect in those cases. I think that would be fine for local use, but it would cause a lot of inconveniences if they are submitted to StashDB. 

I would probably leave it commented out with a warning.

**Comment by bnkai** [comment]
@DogmaDragon thanks for testing. Single word titles is a serious problem. I think it is better to not add it at all then (better to get the image manually than getting a wrong one ) .
I will add the gallery section and try to add back as much from #1107 a possible before merging

**Comment by Flashy78** [comment]
Building off @DogmaDragon version, I added search, the url and performer names to @bnkai image search, which seems to match better. Feel free to add any of it to your PR.
Unfortunately queryURLReplace isn't supported for sceneByName, otherwise adding in @bnkai `%2b` replacement would actually make it work much better. Manually replacing the spaces with + in the query input in Stash will let you find most things.

```
name: Femjoy
sceneByName:
  action: scrapeXPath
  queryURL: "https://www.femjoy.com/videos?s={}"
  scraper: sceneSearch

sceneByQueryFragment:
  action: scrapeXPath
  queryURL: "{url}"
  scraper: sceneScraper

sceneByURL:
  - action: scrapeXPath
    url:
      - femjoy.com
    scraper: sceneScraper

xPathScrapers:
  sceneSearch:
    common:
      $scene: //div[contains(concat(' ', normalize-space(@class), ' '), ' _results_item ') and contains(concat(' ', normalize-space(@class), ' '), ' _results_posts_item ')]
    scene:
      Title:
        selector: $scene//a[@class='preview']/@title
      Date:
        selector: $scene//span[@class='posted_on']/text()
        postProcess: 
          - replace:
              - regex: .+on\s(.+)
                with: $1
          - parseDate: Jan 2, 2006             
      URL:
        selector: $scene//a[@class='preview']/@href
        postProcess:
          - replace:
              - regex: ^
                with: "https://www.femjoy.com"
      Image:
        selector: $scene//img[contains(concat(' ', normalize-space(@class), ' '), ' _image ') and contains(concat(' ', normalize-space(@class), ' '), ' item_cover ')]/@src

  sceneScraper:
    scene:
      Title: //div[@class='post_details']/h1[@class='post_title']/span/text()
      Studio: 
        Name: 
          fixed: Femjoy
      Date: 
        selector: //div[@class='post_details']/h2[@class='post_title']
        postProcess: 
          - replace:
              - regex: .+on\s(.+)
                with: $1
          - parseDate: Jan 2, 2006             
      Performers: 
        Name: //div[@class='post_details']/h1[@class='post_title']/a[contains(@href,"/models/")]
        URL: //div[@class='post_details']/h1[@class='post_title']/a[contains(@href,"/models/")]/@href        
      URL:
        selector: //meta[@property="og:url"]/@content
        postProcess:
          - replace:
              - regex: .*\/
                with: "https://www.femjoy.com/post/"
      Image:
        selector: //div[@class='post_details']/h1[@class='post_title']//text()
        concat: " "
        postProcess:
          - replace:
              - regex: ( in| Add Video to favorites)
                with: ''
              - regex: \s
                with: "%2b" # works better than adding plain + or %20
              - regex: ^
                with: "https://www.femjoy.com/videos?s="
          - subScraper: //img[@class="_image item_cover"]/@src
      Details: //div[@class='post_details']/h2[@class='post_description']/p
# Last Updated November 2, 2022
```

**Pull request merged**
