### PR TITLE
Add performer and scene scrapers for ATK Girlfriends

### PR DESCRIPTION
**Pull request by bacchus-enorches**

### CODE REVIEW

**Comment by bacchus-enorches** [comment]
Large parts of their site are broken or missing, but these should work for the bits that aren&rsquo;t.

**Comment by bacchus-enorches** [comment]
Took some fragment scraper inspiration from #668 which I did not realize already existed.

**Comment by bnkai** [comment]
> Took some fragment scraper inspiration from #668 which I did not realize already existed.

I'll close the other PR once this is ready so take whatever you need from there

**Comment by bacchus-enorches** [comment]
@bnkai go ahead and merge this if you want; model page scraper needs to be Python to preserve some state so it&rsquo;ll take a minute.

**Pull request closed without merging**
