### PR TITLE
add Hotmovies.yml

### PR DESCRIPTION
**Pull request by JaseNZC**
This was put together based on a request.
May need a bit of refinement but its a start and does work although I have not done extensive testing
So it's a case of feel free to go nuts in making changes.

### CODE REVIEW

**Comment by bnkai** [comment]
@JaseNZC is the date actually useful?
The one you get from the script is the date the movie/scene was added to the site not the original release date. I would rather not have a date than have an incorrect one.
From the actual release date they only list the year.
The scene tags selector seems to get the tags only from the first clip and not all clips from the page. Using `//span[@class="list_attributes"]/a` instead fetches all the tags but the tags returned are not distinct (and the distinct values xpath function is not supported )

**Comment by JaseNZC** [comment]
> @JaseNZC is the date actually useful?
> The one you get from the script is the date the movie/scene was added to the site not the original release date. I would rather not have a date than have an incorrect one.
> From the actual release date they only list the year.
> The scene tags selector seems to get the tags only from the first clip and not all clips from the page. Using `//span[@class="list_attributes"]/a` instead fetches all the tags but the tags returned are not distinct (and the distinct values xpath function is not supported )

Yup will remove the date agreed it really serves no purpose.
Is it not possible to enable the function of distinct as I have come across a lot of sites this would be really handy in.

**Comment by JaseNZC** [comment]
Don't think I was awake properly.

**Comment by bnkai** [comment]
I actually found a scene where the date was even more irrelevant
Anyway i did another pass over the scraper
I ended up with this
```yaml
name: Hotmovies
sceneByURL:
  - action: scrapeXPath
    url:
      - hotmovies.com
    scraper: sceneScraper
movieByURL:
  - action: scrapeXPath
    url:
      - hotmovies.com
    scraper: movieScraper
performerByURL:
  - action: scrapeXPath
    url:
      - hotmovies.com/porn-star/
    scraper: performerScraper
performerByName:
  action: scrapeXPath
  queryURL: https://www.hotmovies.com/star_search.php?words={}&searchtype_value=star
  scraper: performerSearch
xPathScrapers:
  sceneScraper:
    scene:
      Title: &title
        selector: //h1[@class="title"]
      Details: &desc
        selector: //span[@class="video_description"]
      Tags:
        Name: //span[@class="list_attributes"]/a
      Performers:
        Name: //div[@class="stars section"]//a
      URL: &url
        selector: //meta[@property="og:url"]/@content
      Movies:
        Name: *title
        URL: *url
      Studio:
        Name: //div[@class="small-4 medium-3 cell video_details"]/a[1]
      Image:
        selector: //div[@class="video_preview_wrapper show-for-medium"]/@style
        postProcess:
          - replace:
              - regex: .*?(https?:\/\/\S*\.jpg).*
                with: $1
  movieScraper:
    movie:
      Name: *title
      Director:
        selector: //a[contains(@href, "/director/")]/text()
      Duration:
        selector: //div[@class="small-4 medium-3 cell video_details"]/span[1]
      Studio:
        Name: //a[contains(@href, "/studio/")]/text()
      Synopsis: *desc
      FrontImage: //div[@class="lg_inside_wrap"]/@data-front | //img[@id="cover"]/@src
      BackImage: //div[@class="lg_inside_wrap"]/@data-back
  performerSearch:
    performer:
      Name: //h3[@class="title"]/a/text()
      URL:
        selector: //h3[@class="title"]/a/@href
        postProcess:
          - replace:
              - regex: ^
                with: https://www.hotmovies.com/
  performerScraper:
    performer:
      URL: //link[@rel="canonical"]/@href
      Name: //h1[@class="title"]/text()
      Gender:
        selector: //strong[text()="Gender:"]/following-sibling::text()[1]
        postProcess:
          - map:
              Trans: transgender_female
      Birthdate:
        selector: //strong[text()="Born:"]/following-sibling::text()[1]
        postProcess:
          - replace:
              - regex: \s\/+.+
                with: ""
              - regex: ^([a-zA-Z]{3})[a-zA-Z]*\s
                with: "$1 "
              - regex: (\d)(st|nd|rd|th)
                with: $1
          - parseDate: Jan 2 2006
      Ethnicity: //strong[text()="Ethnicity:"]/following-sibling::text()[1]
      Country:
        selector: //strong[text()="Birth Place:"]/following-sibling::text()[1]
        postProcess:
          - replace:
              - regex: .+\s+(United\sStates|Italy|France)$
                with: $1
      EyeColor: //strong[text()="Eye Color:"]/following-sibling::text()[1]
      Height:
        selector: //strong[text()="Height:"]/following-sibling::text()[1]
        postProcess:
          - feetToCm: true
      Measurements: //strong[text()="Breast Size:"]/following-sibling::text()[1]
      CareerLength: //strong[text()="Years Active:"]/following-sibling::text()[1]
      FakeTits: //strong[text()="Implants:"]/following-sibling::text()[1]
      Tattoos: //strong[text()="Tattoos:"]/following-sibling::text()[1]
      Piercings: //strong[text()="Piercings:"]/following-sibling::text()[1]
      Image: //img[@id='imgStarGalleryFocus']/@src
      HairColor: //strong[text()="Typical Hair Color:"]/following-sibling::text()[1]
      Details:
        selector: //div[@id="bio_description"]//text()
        concat: "|"
        postProcess:
          - replace:
              - regex: Biography\|
                with: "Biography:\n"
              - regex: \|(Early\sLife|Turn\sOns|Awards)\|
                with: "\n\n$1:\n"
              - regex: \|[^\|]*(Career|Facts|Quotes)\|
                with: "\n\n$1:\n"
              - regex: \|(\d{4})
                with: "\n$1"
              - regex: \|
                with: " "
      Aliases: //strong[text()="Aliases:"]/following-sibling::text()[1]
#Last Updated April 28, 2021

```
It will need a few more additions i think
eg a couple more replaces in the performer countries regex, at least for the most common ones

**Comment by JaseNZC** [comment]
Yeah it would be one of those ones that evolve over time, If you want to merge it now go for it and it can be updated as things are found :-)

**Pull request merged**
