### PR TITLE
This is a python scraper to read torrent files for metadata.

### PR DESCRIPTION
**Pull request by Tweeticoats**
This is a python scraper to read torrent files for metadata.
If the title field contains the filename of a file downloaded or a .torrent file.
It will look through the configured path for torrent files and see if there are metadata tags for description, tags etc.

This uses https://github.com/7sDream/torrent_parser under the MIT licence (included as torrent_parser.py)

### CODE REVIEW

**Comment by bnkai** [comment]
I haven't tested yet is there though a specific reason you chose `title` over `filename` ? If i am not mistaken scene by fragment scrapers should have access to that.

**Comment by bnkai** [comment]
It should be noted that this works for torrents from a specific tracker
Most torrents that  i have available only have a comment section  usually with a url  (or a please seed text ) and a created by /  creation date for metadata

**Comment by dLCarbonX** [comment]
How does this work exactly? I am getting errors

**Comment by Tweeticoats** [comment]
Yes, you give it a json map with a title key with ether the name of a .torrent file or a filename and it will look through torrent files in the directory for the torrent that file came from.
echo '{"title":"test.torrent"}'| python3 torrent.py query

If there are comments, tags or other metadata it can return results but I need to add more error handling and have it return valid json to standard out when something goes wrong.

**Comment by dLCarbonX** [comment]
That still doesn't actually do anything lol
`echo '{"title":"/data/media/pr0n/file.mp4"}' | python3 torrent.py query
{"title": "/data/media/pr0n/file.mp4"}`

**Comment by bnkai** [comment]
Merging this. @Tweeticoats Feel free to make a new PR if you need to make any changes.

**Pull request merged**
