### PR TITLE
Fix PornHub sceneScraper

### PR DESCRIPTION
**Pull request by Diliu94**
Updates to make pornhub scraper work again

### CODE REVIEW

**Comment by Maista6969** [comment]
Unclear on what this is fixing, can you provide a link for a video the old scraper is failing for? This could be a geolocation issue but the old scraper and your version produce identical results for me

**Comment by Diliu94** [comment]
Huh thats odd. The old scraper does not give me the full data for any video because the videodata object that is loaded as $datablob does not exist, so it only returns Title, URL and Image. The VideoObject that is available instead does not have the same structure and does not contain as much information to scrape.

As you say it is possible that pornhub is rolling out new versions of the site gradually over the world. I would estimate the old scraper has been failing for me for at least a few weeks, maybe a couple of months now.

**Comment by Maista6969** [comment]
I was going to say that I'd merge this anyway because both scrapers seemed to work the same, but that was an oversight on my part: the existing scraper works for me, but this version doesn't retrieve the image... we'll definitely have to keep an eye on Pornhub and I hope we can get more feedback from other users to figure out which way they're going with this

**Comment by Ziron** [comment]
Sorry! That was a small error caused by careless copy-pasting as the last action!
The image scraping should be unchanged from the existing version and I have fixed that now

**Comment by Maista6969** [comment]
Thanks, I should have spotted that 😅

**Pull request merged**
