### PR TITLE
Add Fitting-Room Scraper

### PR DESCRIPTION
**Pull request by olimeca**
Add Fitting-Room Scraper. Please review.

### CODE REVIEW

**Comment by halorrr** [comment]
You can get the URL with:
```YAML
URL: //meta[@property="twitter:url"]/@content
```

And I found a hacky way to get the date with a subscraper:
```YAML
Date:
        selector: //head/title/text()
        replace:
          - regex: ^
            with: "https://www.fitting-room.com/search/"
        subScraper:
          selector: //div[@class='main-info']/div/p/text()
          postProcess:
            - replace:
              - regex: th|st|nd
                with:
            - parseDate: January 02 2006
```

**Comment by bnkai** [comment]
@halorrr i tried the search already but it doesn't work correctly
In most of the cases you'll get an irrelevant date as the search results are not good
From the results you would need to search again for the title ( if it is in the first page ) and then get the correct date. Even that is not doable as you have no access to the title from the subscraper. Not worth futher effort imo.
Also if that was ok your regex for the date is missing the `rd` for 3rd and the `st` regex will remove the `st` from `August` :-P

**Comment by bnkai** [comment]
Updating with the URL and adding the albums to the gallery section we get the below
```yaml
name: "FittingRoom"
sceneByURL:
  - action: scrapeXPath
    url:
      - fitting-room.com/videos/
    scraper: sceneScraper
galleryByURL:
  - action: scrapeXPath
    url:
      - fitting-room.com/albums/
    scraper: galleryScraper

xPathScrapers:
  sceneScraper:
    scene:
      Title:
        selector: //head/title/text()
      Details: //meta[@property="twitter:description"]/@content
      Performers:
        Name: //div[@class="info-model"]//p[@class="name"]
      Tags:
        Name: //meta[@property="article:tag"]/@content
      Studio:
        Name:
          fixed: Fitting-Room
      Image: //meta[@property="twitter:image"]/@content
      URL: //meta[@property="twitter:url"]/@content
  galleryScraper:
    gallery:
      Title:
        selector: //head/title/text()
      Details: //meta[@property="twitter:description"]/@content
      Performers:
        Name: //div[@class="info-model"]//p[@class="name"]
      Tags:
        Name: //meta[@property="article:tag"]/@content
      Studio:
        Name:
          fixed: Fitting-Room
      URL: //meta[@property="twitter:url"]/@content

# Last Updated October 23, 2020
```

**Comment by halorrr** [comment]
@bnkai Ah fair enough, in the scenes I had tried it had all pulled the right date, must have gotten lucky by trying more recent scenes

**Pull request merged**
