### PR TITLE
Update Kink, switch to CDP

### PR DESCRIPTION
**Pull request by bnkai**
It seems that kink now detects and 403s the plain scraper
Switching to CDP seems to work ok

### CODE REVIEW

**Comment by tolotos68** [comment]
Hi, I don't get any results on macOS, Chrome CDP Path is /Applications/Google Chrome.app/Contents/MacOS/Google Chrome (which should work afaik)

**Comment by bnkai** [comment]
@tolotos68 do other CDP scrapers work?  Brazzers for example (or any that have CDP in the reqs https://github.com/stashapp/CommunityScrapers/blob/master/SCRAPERS-LIST.md)  ? do you get an error in the log ?
I have a version that adds a cookie section can you perhaps try the below?
`Kink.yml`
```yaml
name: kink
sceneByURL:
  - action: scrapeXPath
    url:
      - kink.com
    scraper: sceneScraper

sceneByFragment:
  action: scrapeXPath
  queryURL: https://www.kink.com/shoot/{filename}
  # constructs the scene URL from the filename, provided that the filename includes the scene id
  queryURLReplace:
    filename:
      # the id in kink.com is a 1-6 digit number
      - regex: ^(\d+)[^\d].* # support filenames in the form 12345_performer_other_data.mp4
        with: $1
      - regex: .*\((\d+)\)\.[a-zA-Z\d]+$ #support filenames in the form scene - date - performer (12345).mp4
        with: $1
  scraper: sceneScraper

xPathScrapers:
  sceneScraper:
    scene:
      Title: //meta[@name="twitter:title"]/@content
      Date:
        selector: //span[@class="shoot-date"]/text()
        postProcess:
          - parseDate: January 2, 2006
      Details:
        selector: //span[@class="description-text"]/*[self::p or self::ul]
        concat: "\n\n"
      Performers:
        Name:
          selector: //p[@class="starring"]/span[@class="names h5"]/a/text()
          postProcess:
            - replace:
                - regex: \,
                  with: ""
      Tags:
        Name:
          selector: //a[@class="tag"]
          postProcess:
            - replace:
                - regex: \,
                  with: ""
      Image: //meta[@name="twitter:image"]/@content
      Studio:
        Name:
          selector: //div[@class="column shoot-logo"]/a/@href
          postProcess:
            - replace:
                - regex: /channel/
                  with: ""
      URL: //link[@rel="canonical"]/@href
driver:
  cookies:
    - Cookies:
        - Name: "ct"
          Domain: "www.kink.com"
          Value: "0"
          Path: "/"
  useCDP: true
# Last Updated January 31, 2022
```

**Comment by tolotos68** [comment]
> @tolotos68 do other CDP scrapers work? Brazzers for example (or any that have CDP in the reqs https://github.com/stashapp/CommunityScrapers/blob/master/SCRAPERS-LIST.md) ? do you get an error in the log ? I have a version that adds a cookie section can you perhaps try the below? `Kink.yml`<

Hi, seems that my Chrome got messed up. After setting up a docker-based headless chrome everything works fine now. Sorry...

**Comment by bnkai** [comment]
> > @tolotos68 do other CDP scrapers work? Brazzers for example (or any that have CDP in the reqs https://github.com/stashapp/CommunityScrapers/blob/master/SCRAPERS-LIST.md) ? do you get an error in the log ? I have a version that adds a cookie section can you perhaps try the below? `Kink.yml`<
> 
> Hi, seems that my Chrome got messed up. After setting up a docker-based headless chrome everything works fine now. Sorry...

Despite your  chrome being messed up i think there is still an issue when using CDP via path and not via an http connection (eg remote instance). A user in discord reported that at least (issue with cloudflare denying access). Anyway thanks for the feedback.

**Pull request merged**
