### PR TITLE
Fix RealJamVR scraper

### PR DESCRIPTION
**Pull request by Emilo2**
- Fixed to work with the new layout
- Added studio code from the trailer URL
- Added gallery scraping

### CODE REVIEW

**Review by JackDawson94 — CHANGES_REQUESTED** [review]
Testing, made an error in my previous comment, resuming testing

**Comment by Maista6969** [comment]
This could use another look after the merge of #1387 so we can get galleries from this scraper 👍

**Review by Maista6969 — CHANGES_REQUESTED** [review]
Will need to pull in the changes from master and resolve the conflicts arising from #1387

**Comment by Emilo2** [comment]
Merged from master.

#1387 failed to fetch multiple performers and this should fix it.
Also the additional tags should be properly fetched now.

**Review by Maista6969 — APPROVED** [review]

**Pull request merged**
