### PR TITLE
Add support for loading markers for Vixen Media Group content

### PR DESCRIPTION
**Pull request by existing-paradox**
There are also some additional error handling features that may or may not be wanted

### CODE REVIEW

**Comment by existing-paradox** [comment]
I am working on updating to support match v0.24.x

**Comment by existing-paradox** [comment]
Can confirm this now works with updated schema

**Comment by existing-paradox** [comment]
I am fairly certain that is a limitation of the Stash GraphQL configuration, I am not seeing a query supporting ignore case. To handle this, I watched the warning logs and added aliases where necessary then rerunning the scrape. It's not perfect but doesn't require too much extra effort.

**Comment by existing-paradox** [comment]
The tag alias method has been tested and works. The name of the marker will be named what ever the the chapter title is set as from Vixen API, not the name of the primary tag defined in marker.

This functionality is based on the functionality used by the MindGeekAPI.

**Comment by existing-paradox** [comment]
I have also seen chapter titles misspelled. You can't always programmatically solve for every edge case 😁

**Comment by Maista6969** [comment]
But we can certainly match tags without considering their case: would this work?
```python
def graphql_findTagbyName(name):
    query = """
        query {
            allTags {
                id
                name
                aliases
            }
        }
    """
    result = callGraphQL(query)
    normalized_name = name.lower().strip()
    for tag in result["allTags"]:
        if tag["name"].lower() == normalized_name:
            return tag["id"]
        if tag.get("aliases"):
            for alias in tag["aliases"]:
                if alias.lower() == normalized_name:
                    return tag["id"]
    return None
```

**Comment by existing-paradox** [comment]
@Maista6969 good call! Not sure why I didn't think of that... Update coming soon

**Pull request merged**
