### PR TITLE
Add Teencoreclub xPath scraper

### PR DESCRIPTION
**Pull request by hyde231**

### CODE REVIEW

**Comment by halorrr** [comment]
Poking around on this from a random site on the list.

The date is a partial (only the year) which is something stash can't parse right now.

There seems to be some weirdness if multiple performers are in a scene:
On this one for instance https://bangteenpussy.com/video/19246/bic-1247555289 on the page looks fine but when we scrape it, there are a ton of tabs between the names (which seems to be how it is in the page source.

Sometimes if there are multiple models they just straight leave the title blank https://bangteenpussy.com/video/19244/bic-83015 not much we can do about that though

I've only tested these on the one site so far but looks like:

You can get Tags with:
```
      Tags:
        Name:
          selector: //meta[@name="keywords"]/@content
          split: ','
```

This works for Studio:
```
      Studio:
        Name:
          selector: //div[@class="flex-shrink-0 flex items-center"]//img[1]/@alt
          replace:
            - regex: \.\w+
              with: 
```

**Comment by halorrr** [comment]
This fixes all the potential tabs in the title:
```
      Title:
        selector: //div[@class="detail-hero-title"]//h1/text()
        replace:
          - regex: \t+
            with: ' '
```

And this does the same for performers and splits the string so we can read multiple performers:
```
      Performers:
        Name:
          selector: //div[@class="detail-hero-title"]//h1/text()
          replace:
            - regex: \t+
              with:
          split: ','
```

**Comment by halorrr** [comment]
These sites don't work with this scrape as they are entirely different layouts (and one is a cam site) 
```
https://www.nightclubcams.com/
https://www.nightclub.eu/
https://letsgodirty.com/
```

Tags & Studio seem to work on all the sites in my tests. 

We also try and throw a comment at the bottom of newer scrapers with their last updated date.

With all my comments this looks like it should work:
```
name: "Teencoreclub"
sceneByURL:
  - action: scrapeXPath
    url:
      - https://analyzedgirls.com/
      - https://assteenmouth.com/
      - https://bangteenpussy.com/
      - https://brutalinvasion.com/
      - https://cumaholicteens.com/
      - https://defiled18.com/
      - https://doubleteamedteens.com/
      - https://dreamteenshd.com/
      - https://girlsgotcream.com/
      - https://hardcoreyouth.com/
      - https://littlehellcat.com/
      - https://maketeengape.com/
      - https://nylonsweeties.com/
      - https://seductive18.com/
      - https://teenanalcasting.com/
      - https://teendrillers.com/
      - https://teensnaturalway.com/
      - https://teenstryblacks.com/
      - https://spermantino.com/
      - https://teachmyass.com/
      - https://drilledchicks.com/
      - https://analcheckups.com/
      - https://fabsluts.com/
      - https://jerk-offpass.com/
      - https://nylonspunkjunkies.com/
      - https://shegotsix.com/
      - https://spearteenpussy.com/
      - https://teencoreclub.com/
      - https://teencorezine.com/
      - https://teensgoporn.com/
      - https://weneednewtalents.com/
      - https://xcoreclub.com/
      - https://youngthroats.com/
      - https://tryteens.com/
      - https://whiteteensblackcocks.com/
    scraper: sceneScraper
xPathScrapers:
  sceneScraper:
    scene:
      Title:
        selector: //div[@class="detail-hero-title"]//h1/text()
        replace:
          - regex: \t+
            with: ' '
      Details: //div[@class="detail-description"]/text()
      Performers:
        Name:
          selector: //div[@class="detail-hero-title"]//h1/text()
          replace:
            - regex: \t+
              with:
          split: ','
      Tags:
        Name:
          selector: //meta[@name="keywords"]/@content
          split: ','
      Image:
        selector: //div[@class="detail-hero"]/@style
        replace:
          - regex: ^.*url.([^\)]+).*$
            with: "$1"
      Studio:
        Name:
          selector: //div[@class="flex-shrink-0 flex items-center"]//img[1]/@alt
          replace:
            - regex: \.\w+
              with:

# Last Updated June 20, 2020
```

**Comment by hyde231** [comment]
Thanks for testing. Is there any testing framework available, or is it all manual?

**Comment by halorrr** [comment]
It is all manual

**Pull request merged**
