### PR TITLE
Duplicating parsing from LegalPorno into Pornworld

### PR DESCRIPTION
**Pull request by ryosaeba75**
Both sites are similar. This add performerByURL and sceneByScrapper Pornworld scrapper.

### CODE REVIEW

**Comment by ryosaeba75** [comment]
Does this need anything on my side or is it just waiting for approval?

**Comment by bnkai** [comment]
@ryosaeba75 I haven't had the chance to test/check the scraper yet. Xpath/JSON ones are easier/faster to check so script scrapers usually end up at the bottom of the backlog. I will definitely check it out before the weekend.

**Comment by Belleyy** [comment]
Is there any reason to use a python script instead of a scrapeJson for sceneByFragment ?

**Comment by Belleyy** [comment]
Is there any reason why using a python script instead of a JSON scraper ?
Tested a JSON scraper and it work.

**Comment by ryosaeba75** [comment]
@bnkai no worries, I was just checking to be sure that wasn't something missing on my side.
@Belleyy not sure, I just duplicated the one from legalporno as the website are similar. They probably sould be merged but I wasn't sur how to do that, especially for the `sceneByFragment` part.

**Comment by bnkai** [comment]
It seems that the only thing the script does is clear the filename and get the id to search for.
We can now do that using `queryURLReplace` so i would suggest closing this PR in favor of #687

**Comment by Belleyy** [comment]
> Is there anyway to have a common `sceneByFragment` for legalporno and pornworld? I know that it's possible for `sceneByUrl`but not sur how for `sceneByFragment`. 

No you can't have multiple `sceneByFragment` in a yml. 

> That could be the only reason to favor python over the classic yml/xpath scrapper.

How so ? Your python right now only deal with Pornworld too, and to launch the script you still need a yml file so you are limited with `sceneByFragment`, only way to have a common is having a script that search on Pornworld then on Legalporno.

**Comment by ryosaeba75** [comment]
Yes your edit is what I was thinking about, having two yml referencing a single python, with probably a parameter to make the distinction between both srapper. But as you noted, right now either my scrapper nor your's deal with both so for now there is no use for python. I'm closing this PR in favor of your's and if/when I (or someone) else merge both scrappers (via a common python file) it will be another PR.

**Pull request closed without merging**
