### PR TITLE
xpath, improvement: Add tags to Grooby

### PR DESCRIPTION
**Pull request by nrg101**
Grooby sites appear to have recently added tags to their scenes.

This change adds tag scraping.

It also adds support for additional Grooby network sites.

Tested as working for scenes at various sites. Have not been able to confirm the gallery scraping with tags is working or not, as galleries seem to be not accessible in the free/preview/tour view of the sites.

### CODE REVIEW

**Review by JackDawson94 — COMMENTED** [review]
Tags are working.
Cover images are not pulled though, is this intended ? 
example: https://www.femout.xxx/tour/trailers/Come-Play-With-Me.html

**Comment by nrg101** [comment]
ok, let's try every domain listed to see if the image is scraped:

✔️ https://www.asiantgirl.com/tour/trailers/Helen-Nancy.html
✔️ https://www.blacktgirlshardcore.com/tour/trailers/Caramel-God-is-Balls-Deep-in-Baad-Girl-Ari.html
✔️ https://www.black-tgirls.com/tour/trailers/Girl-of-the-Month-Carter.html
✔️ https://www.bobstgirls.com/tour/trailers/Miran-Doll.html
❌ https://www.femout.xxx/tour/trailers/Come-Play-With-Me.html
✔️ https://www.femoutsex.xxx/tour/trailers/Here-Kitty-Kitty.html
✔️ https://www.franks-tgirlworld.com/tour/trailers/Esmond-Will-Make-You-Hard.html
✔️ https://www.grooby-archives.com/tour/trailers/Tessa-Jaynes-First-Hardcore.html
✔️ https://www.groobygirls.com/tour/trailers/Introducing-Amber-Analeise.html
✔️ https://www.ladyboy-ladyboy.com/tour/trailers/Helen-Nancy.html
✔️ https://www.ladyboy.xxx/tour/trailers/Pans-Climax.html
❌ https://www.realtgirls.com/tour/trailers/Roxanne-Rom-Kelly-Quell-Get-Down.html
✔️ https://www.tgirlsex.xxx/tour/trailers/Maid-Mari-Loves-Dick.html
✔️ https://www.tgirls.porn/tour/trailers/SUCKERS-Eros-and-Cherry-Love-It.html
✔️ https://www.tgirls.xxx/tour/trailers/Minx-Maven-Magic.html
✔️ https://www.tgirlshookup.com/tour/trailers/Pocket-Sized-Fleshlight-Gets-Stretched-Out.html
✔️ https://www.tgirltops.com/tour/trailers/Topped-By-Natalee-Skye.html
✔️ https://www.transexpov.com/tour/trailers/Kalli-Grace-Rides-Again.html
✔️ https://www.transgasm.com/tour/trailers/Kylie-Stixxxs-Climax.html
❌ https://www.transnificent.com/tour/trailers/Price-is-Ready-to-Play-With-You.html

It looks like 3 of the sites have had some redesign which means the xpath for the cover image no longer works... I'll see if I can get it adjusted to work with the 3 failing site examples above.

**Comment by nrg101** [comment]
@JackDawson94, I changed the image scraping to combine the canonical link and relative URL for the cover image and it is now working for all studios/domains:

✔️ https://www.asiantgirl.com/tour/trailers/Helen-Nancy.html
✔️ https://www.blacktgirlshardcore.com/tour/trailers/Caramel-God-is-Balls-Deep-in-Baad-Girl-Ari.html
✔️ https://www.black-tgirls.com/tour/trailers/Girl-of-the-Month-Carter.html
✔️ https://www.bobstgirls.com/tour/trailers/Miran-Doll.html
✔️  https://www.femout.xxx/tour/trailers/Come-Play-With-Me.html
✔️ https://www.femoutsex.xxx/tour/trailers/Here-Kitty-Kitty.html
✔️ https://www.franks-tgirlworld.com/tour/trailers/Esmond-Will-Make-You-Hard.html
✔️ https://www.grooby-archives.com/tour/trailers/Tessa-Jaynes-First-Hardcore.html
✔️ https://www.groobygirls.com/tour/trailers/Introducing-Amber-Analeise.html
✔️ https://www.ladyboy-ladyboy.com/tour/trailers/Helen-Nancy.html
✔️ https://www.ladyboy.xxx/tour/trailers/Pans-Climax.html
✔️  https://www.realtgirls.com/tour/trailers/Roxanne-Rom-Kelly-Quell-Get-Down.html
✔️ https://www.tgirlsex.xxx/tour/trailers/Maid-Mari-Loves-Dick.html
✔️ https://www.tgirls.porn/tour/trailers/SUCKERS-Eros-and-Cherry-Love-It.html
✔️ https://www.tgirls.xxx/tour/trailers/Minx-Maven-Magic.html
✔️ https://www.tgirlshookup.com/tour/trailers/Pocket-Sized-Fleshlight-Gets-Stretched-Out.html
✔️ https://www.tgirltops.com/tour/trailers/Topped-By-Natalee-Skye.html
✔️ https://www.transexpov.com/tour/trailers/Kalli-Grace-Rides-Again.html
✔️ https://www.transgasm.com/tour/trailers/Kylie-Stixxxs-Climax.html
✔️  https://www.transnificent.com/tour/trailers/Price-is-Ready-to-Play-With-You.html

**Review by JackDawson94 — APPROVED** [review]
Looks good 👍 Kind of a weird image path but it works !

**Pull request merged**
