### PR TITLE
add InterrcialPass.com to html scene scrapers

### PR DESCRIPTION
**Pull request by SabinBC**
InterracialPass.yml to use URL to scrape scene by scene

### CODE REVIEW

**Comment by JaseNZC** [comment]
That site is the same layout as erotiquetvlive.com , I did it a month or so ago but forgot to PR it.
Here is the code for it feel free to merge it into yours to cover both sites.
Performers change to a different layout part way through.
`name: ErotiqueTVLlive
sceneByURL:
  - action: scrapeXPath
    url:
      - erotiquetvlive.com
    scraper: sceneScraper
xPathScrapers:
  sceneScraper:
    scene:
      Title:
        selector: //div[@class="video-player"]/div[@class="title-block"]/h2[@class="section-title"]
      Performers:
        Name: //ul[@class="half-sized"]//a | //div[@class="update-info-block models-list-thumbs"]
      Tags:
        Name: //ul[@class="tags"]//a
      Details:
        selector: //h3[contains(.,"Description:")]/following-sibling::text()
      Image:
        selector:  //script[contains(text(),'text(remaining)')]/text()
        postProcess:
          - replace:
              - regex: .+(?:poster=")([^"]*).+
                with: https://erotiquetvlive.com$1
      Studio:
        Name:
          fixed: ErotiqueTVLlive
# Last Updated April 08, 2021`

**Comment by bnkai** [comment]
Combining/fixing the above i get this
```yaml
name: "InterracialPass"
sceneByURL:
  - action: scrapeXPath
    url:
      - erotiquetvlive.com
      - interracialpass.com/
    scraper: sceneScraper
xPathScrapers:
  sceneScraper:
    scene:
      Title: //div[@class="video-player"]/div[@class="title-block"]/h2[@class="section-title"]
      Date:
        selector: //div[@class="update-info-row"]/strong[contains(.,"Released")]/following-sibling::text()
        postProcess:
          - parseDate: January 2, 2006
      Details:
        selector: //h3[contains(.,"Description:")]/following-sibling::text()
      Tags:
        Name: //ul[@class="tags"]//a
      Performers:
        Name: //div[@class="update-info-block models-list-thumbs"]//span|//ul[@class="half-sized"]//a
      Image:
        selector: //base/@href|//div[@class="player-thumb"]//img/@src0_1x
        concat: "|"
        postProcess:
          - replace:
              - regex: '/(tour|t1)/\|'
                with: ""
# Last Updated June 5, 2021
```
@JaseNZC  do you remember any scenes that required the alternative perf selector? I tried to find some but coulldnt

**Comment by JaseNZC** [comment]
> Combining/fixing the above i get this
> 
> ```yaml
> name: "InterracialPass"
> sceneByURL:
>   - action: scrapeXPath
>     url:
>       - erotiquetvlive.com
>       - interracialpass.com/
>     scraper: sceneScraper
> xPathScrapers:
>   sceneScraper:
>     scene:
>       Title: //div[@class="video-player"]/div[@class="title-block"]/h2[@class="section-title"]
>       Date:
>         selector: //div[@class="update-info-row"]/strong[contains(.,"Released")]/following-sibling::text()
>         postProcess:
>           - parseDate: January 2, 2006
>       Details:
>         selector: //h3[contains(.,"Description:")]/following-sibling::text()
>       Tags:
>         Name: //ul[@class="tags"]//a
>       Performers:
>         Name: //div[@class="update-info-block models-list-thumbs"]//span|//ul[@class="half-sized"]//a
>       Image:
>         selector: //base/@href|//div[@class="player-thumb"]//img/@src0_1x
>         concat: "|"
>         postProcess:
>           - replace:
>               - regex: '/(tour|t1)/\|'
>                 with: ""
>       Studio:
>         Name: //a[@class="navbar-brand"]
> # Last Updated June 5, 2021
> ```
> 
> @JaseNZC do you remember any scenes that required the alternative perf selector? I tried to find some but coulldnt

There is this one 
[https://erotiquetvlive.com/tour/trailers/maddy-riley-reid-share-a-cock.html](url) which I have used the //span|//ul[@class="half-sized"]//a for , most of the other ones use the other one.

**Comment by bnkai** [comment]
@JaseNZC 
`//div[@class="update-info-block models-list-thumbs"]//span` works fine even with the url you posted, no need for the extra selector.
I will merge with just that. If by any chance you find a scene that doesnt work we can update later

**Pull request merged**
