### PR TITLE
Adds AngelaWhite xPath scraper

### PR DESCRIPTION
**Pull request by halorrr**
Really not much useful metadata on this site but this fills a request from https://github.com/stashapp/CommunityScrapers/issues/73

### CODE REVIEW

**Comment by bnkai** [comment]
Some sites are not worth it  i agree. If it was requested though then i guess its ok

**Comment by bnkai** [comment]
With a little extra effort we might be able to extract performers, tags and an image.
The trick is to use `http://angelawhite.com/tour/search?query=xxx` ( where xxx is the scene number, eg 098 ) and subScraper like i used in bangbros to get the dates.
The image is doable
```yaml
Image:
  selector: //div[@class="video-details-inner"]/h2/text()
  replace:
    - regex: (^\d+)\s.+
      with: "http://angelawhite.com/tour/search?query=$1"
  subScraper:
     selector: //img[@class="set-target-188 thumbs stdimage"]/@src
     replace:
       - regex: ^
       with: http://angelawhite.com
```
The tags and performers will need the `split` function implemented first since subscraper only returns one string as result

**Comment by halorrr** [comment]
Hmmm, how far out do you think the split function is? Should we just consider this one blocked until that is around, since its meta value is minimal anyway on this scraper?

**Comment by bnkai** [comment]
I'll tag it as blocked and add the extra code for performers,tags when split is ok.
@halorrr can you test and update the performer image part? I tried in a few scenes only.
Be careful with the spaces in the yaml

**Comment by bnkai** [comment]
The below code is the final i came up.
The performers and tags need the `split` function that is still a PR  https://github.com/stashapp/stash/pull/579
```yaml
name: "AngelaWhite"
sceneByURL:
  - action: scrapeXPath
    url:
      - angelawhite.com/tour/trailers/
    scraper: sceneScraper
xPathScrapers:
  sceneScraper:
    common:
      $info: //div[@class="video-details-inner"]
      $search: //div[@class="video-details-inner"]/h2/text()
    scene:
      Title: $info/h2/text()
      Date:
        selector: $info/span/text()
        parseDate: Jan 2, 2006
      Details: $info//p/text()
      Performers:
        Name:
          selector: $search
          replace:
            - regex: (^\d+)\s.+
              with: "http://angelawhite.com/tour/search?query=$1"
          subScraper:
            selector: //div[@class="models-list"]/a/text()
            concat: ","
          split: ","
      Tags:
        Name:
          selector: $search
          replace:
            - regex: (^\d+)\s.+
              with: "http://angelawhite.com/tour/search?query=$1"
          subScraper:
            selector: //div[@class="categories-list"]/a/text()
            concat: ","
          split: ","
      Image:
        selector: $search
        replace: 
          - regex: \s
            with: "+"
          - regex: ^
            with: "http://angelawhite.com/tour/search?query=\""
          - regex: $
            with: "\""
        subScraper:
          selector: //img/@src0
          replace:
            - regex: ^
              with: http://angelawhite.com
# Last Updated June 17, 2020
```

**Comment by halorrr** [comment]
Updated with the above as well as added an xPath to scrape the studio name. This turned out to me a much more complete scraper.

**Pull request merged**
