### PR TITLE
Clips4Sale: Update

### PR DESCRIPTION
**Pull request by peolic**
- add studio
- use `common` for `.clipInfo` selector
- optimize date
- concat details by two empty lines

✅ tested

### CODE REVIEW

**Comment by bnkai** [comment]
Look ok.
Should we also replace the concat in the details section ?
```yaml
      Details:
        selector: //div[@class="clip"]/div/p//text()
        concat: "\n\n"
        postProcess:
          - replace:
              - regex: "Description:"
                with:
```
I think concating by `\n\n` instead of the space maintains better the original form of the description text.

**Comment by peolic** [comment]
>I think concating by \n\n instead of the space maintains better the original form of the description text.

Yeah I agree.

Also, I found that the `//text()` selector sometimes discards some of the description.
I changed mine locally to `//div[@class="clip"]/div/p//*`.

To be fair, studios on Clips4Sale can put 'more' than plain text in their video description, which means I can't be sure that the new selector isn't worse for studios other than the ones I regularly scrape.

**Comment by bnkai** [comment]
>To be fair, studios on Clips4Sale can put 'more' than plain text in their video description, which means I can't be sure that the new selector isn't worse for studios other than the ones I regularly scrape.

Yeah i noticed that too in another scraper. 

> Also, I found that the `//text()` selector sometimes discards some of the description.
> I changed mine locally to `//div[@class="clip"]/div/p//*`.

Do you want to update that also or should i merge?

**Comment by peolic** [comment]
> Do you want to update that also or should i merge?

You can go ahead and merge

**Pull request merged**
