### PR TITLE
add ThirdSexXXX scrapper

### PR DESCRIPTION
**Pull request by SuperScrapper**

### CODE REVIEW

**Comment by peolic** [comment]
Seems like this scraper can be made using "pure" YAML (without a Python dependency),
that's always preferred over script-based scrapers.

**Comment by peolic** [comment]
```yml
name: ThirdSexXXX

sceneByURL:
  - action: scrapeXPath
    scraper: sceneScraper
    url:
      - thirdsexxxx.com/trailers

xPathScrapers:
  sceneScraper:
    scene:
      Title: //div[@class="memberPicV"]/h2
      Date:
        selector: //div[@class="info"]/p[contains(., "Added")]
        postProcess:
          - replace:
              - regex: "^Added: +(\\d+)/(\\d+)/(\\d+) .+$"
                with: $3-$1-$2
      Details: //div[@class="description"]/p
      Performers:
        Name: //div[@class="info"]/p[contains(., "Starring")]/a
      Studio:
        Name:
          fixed: ThirdSexXXX
      Tags:
        Name: //div[contains(@class, "tags")]//a
      Image:
        selector: //div[@class='player-thumb']/img/@src0_1x
        postProcess:
          - replace:
              - regex: ^/
                with: https://thirdsexxxx.com/

# Last Updated December 26, 2021
```

**Comment by SuperScrapper** [comment]
> Seems like this scraper can be made using "pure" YAML (without a Python dependency), that's always preferred over script-based scrapers.

I suspected that I would receive this feedback. I wrote this a while back before understanding the syntax of the `pure` YAML way. I've converted it to `pure` YAML before noticing that you've already done so, but it was good practice anyway, and seeing your approach taught me something new, so thank you!

Here's my approach for reference.
```yaml
name: ThirdSexXXX

sceneByURL:
  - action: scrapeXPath
    url:
      - thirdsexxxx.com/trailers
    scraper: sceneScraper

xPathScrapers:
  sceneScraper:
    common:
      $info: //div[@class="info"]
    scene:
      Title:
        selector: //title
        postProcess:
          - replace:
            - regex: .+\|(.+)
              with: $1
      Image: //meta[@property="og:image"]/@content
      Date:
        selector: $info
        postProcess:
          - replace: 
              - regex: .+Added:\s*(\d{2}\/\d{2}\/\d{4}).+
                with: $1
          - parseDate: 01/02/2006
      Performers:
        Name:
          selector: $info/p/a
      Details:
        selector: //div[@class="description"]/p
        concat: "\n\n"
      Tags:
        Name:
          selector: //div[@class="tags clear"]//a
      Studio:
        Name:
          fixed: ThirdSexXXX

# Last Updated December 26, 2021
```

**Comment by bnkai** [comment]
@SuperScrapper do you want to combine your and @peolic 's xPath scraper?
eg your image part is simpler while @peolic 's title is simpler....

**Pull request merged**
