### PR TITLE
Create Swallowed.yml

### PR DESCRIPTION
**Pull request by trocolodito**
Scene Scraper for Swallowed.com

### CODE REVIEW

**Comment by SpedNSFW** [comment]
There's already a scraper for swallowed.com.
https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/nympho.yml

**Comment by bnkai** [comment]
@trocolodito  can you close the PR ?
I added dates for the already existing nympho.yml #277

**Comment by trocolodito** [comment]
> @trocolodito can you close the PR ?

Sorry but a bit newbie here. How can I do that?

**Comment by trocolodito** [comment]
Ok done

**Pull request closed without merging**
