### PR TITLE
add Hitzefrei.yml

### PR DESCRIPTION
**Pull request by JaseNZC**

### CODE REVIEW

**Comment by bnkai** [comment]
Added the performer URL in the scene scraper and a performer scraper ( weight needs  to be commented out atm or the build from <https://github.com/stashapp/stash/pull/1337> )
```yaml
name: Hitzefrei
sceneByURL:
  - action: scrapeXPath
    url:
      - hitzefrei.com
    scraper: sceneScraper
performerByURL:
  - action: scrapeXPath
    url:
      - hitzefrei.com/model
    scraper: performerScraper
xPathScrapers:
  sceneScraper:
    scene:
      Title:
        selector: //div[@class="row-content-details"]/h1
      Date:
        selector: //span[@class="meta-value"][2]/text()
        postProcess:
          - parseDate: 02/01/2006
      Performers:
        Name: //div[@class="model-name"]
        URL: //div[@class="model-thumb"]/a/@href
      Details: //div[@class="content-description"]/p
      Image:
        selector: //video[@id="ypp-player"]/@poster
      Studio:
        Name:
          fixed: Hitzefrei
  performerScraper:
    common:
      $stat: p[@class="stat-value"]
    performer:
      Name: //h1[@class="model-name"]
      Details: //div[@class="model-profile"]
      Image: //div[contains(@class,"model-thumbnail")]/img/@src
      Birthdate:
        selector: //div[p[text()="Birthdate"]]/$stat
        postProcess:
          - parseDate: 2006-01-02
      Measurements: //div[p[text()="Measurements"]]/$stat
      Weight:
        selector: //div[p[text()="Weight"]]/$stat
        postProcess:
          - replace:
              - regex: (\d+)\s.+
                with: $1
          - lbToKg: true
      Height:
        selector: //div[p[text()="Height"]]/$stat
        postProcess:
          - feetToCm: true
      HairColor: //div[p[text()="Hair"]]/$stat
      EyeColor: //div[p[text()="Eyes"]]/$stat
# Last Updated April 25, 2021
```
Can you update  (scraper + extra check for performer  in scraper list) if it checks out for you ?

**Comment by JaseNZC** [comment]
Did not even think about adding performer , Everything works as expected, have commented out weight with note.

**Comment by bnkai** [comment]
Yeah looks good, can you replace 7 with `v0.6.0-49` ?
We could also either uncommend and add `v0.6.0-49` in the `reqs` part of the scraper list file. ( you forgot to add the check for the performer there)

**Comment by JaseNZC** [comment]
Done :-)

**Pull request merged**
