### PR TITLE
Add Killergram xPath scene scraper

### PR DESCRIPTION
**Pull request by bnkai**
Requested from #73 
The title is mostly a hack, it seems to work though. Not sure if there is a better alternative

### CODE REVIEW

**Comment by JaseNZC** [comment]
Seems all ok to me.

**Comment by bnkai** [comment]
> Seems all ok to me.

Since someone made an effort to create all the subsites in stashdb i edited the studio selector to return those instead and i left the `Killegram` one commented out. The only one i think i left out is the `Killegram cuts` that are behind paywall.
@JaseNZC can you do a quick proof reading wwhen you get the chance?

**Comment by JaseNZC** [comment]
> > Seems all ok to me.
> 
> Since someone made an effort to create all the subsites in stashdb i edited the studio selector to return those instead and i left the `Killegram` one commented out. The only one i think i left out is the `Killegram cuts` that are behind paywall. @JaseNZC can you do a quick proof reading wwhen you get the chance?

Yup will do

**Comment by JaseNZC** [comment]
Have gone over each one and all seems ok to me.
Stupid they make one site behind a paywall seems pointless.

**Comment by BlokeCDP** [comment]
Great work guys - thank you :)

**Comment by BlokeCDP** [comment]
Hi guys - just a few mapping changes - again I'm not familiar with editing/committing:

lets get slippy: Let's Get Slippy
space hoppers: Space Hoppers And Lolly Poppers

**Pull request merged**
